### ISSUE TITLE
automatisation des boutons link

### ISSUE THREAD

**Issue by vberthiaume** [GRIS-UdeM/SpatGRIS-legacy#108]
Est-ce que c'est quelque chose qu'on veut?

**Comment by Normandeau** [comment]
Voir l'issue #96. Comme tu l'as fermée, je suppose que c'est fait! Donc non seulement on veut les boutons Link, mais surtout la fonction qui va avec: une ligne d'écriture seulement pour la source no 1.

**Comment by vberthiaume** [comment]
voir #118 pour la 2e partie de cette issue

**Comment by vberthiaume** [comment]
Je veux juste mentionner que ces changements sont non-triviaux. Comme link est une valeur entière, comme le movement mode, cette automation ne fonctionnera pas bien dans DP jusqu'à temps qu'on utilise des paliers (voir #104).
