### ISSUE TITLE
Imprécision de l'écriture de l'automation dans Logic X

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#109]
Bonjour,
Il y a eu pas mal de discussions privées à ce sujet ici récemment mais il n'en reste aucune trace dans Github. Il serait mieux d’utiliser ce site pour la description des bogues. Car cette discussion a eu lieu maintes fois depuis huit ans. En gardant une trace de celles-ci, cela nous évite d'avoir à relancer les mêmes discussions à tous les deux ans.
Essentiellement on peut dire que:
- les séquenceurs ne sont pas très performants sur le plan de l'écriture de l'automation
- que Reaper et Logic n'ont , semble-t-il, aucun réglages pour affiner l'écriture de ces paramètres
- que DP permet d'écrire plus ou moins finement l'automation
- qu'une grande quantité de données d'automation alourdit singulièrement le processeur
- qu'il semble que les cartes graphiques soient davantage responsables du niveau de performance que les disque durs.

Comparaison SpatGRIS 0.18-ZirkOSC 3.10-Octogris 3.06-toutes versions AU
En attendant, voici ce que j'ai testé avec mon Mac, qui est le plus rapide que nous ayons sous la main pour le moment (disque SSD, 16Gb RAM, 4 cœurs 2,7GHz. écran Retina):
- 8 pistes stéréo -> sortie octophonique, Mode Touch
- piste 1: SpatGRIS, écriture manuelle. mode Pan Volume, automation visible au moment de l'écriture
- piste 2: SpatGRIS, écriture manuelle. mode OSCSpatialisation, automation visible au moment de l'écriture
- piste 3: SpatGRIS, écriture d'une trajectoire. mode Pan Volume, automation invisible au moment de l'écriture
- piste 4: SpatGRIS, écriture manuelle. mode Pan Volume, automation invisible au moment de l'écriture.
- piste 5: ZirkOSC, écriture manuelle. mode OSC, automation visible au moment de l'écriture
- piste 6: ZirkOSC, écriture d'une trajectoire. mode OSC, automation invisible au moment de l'écriture
- piste 7: ZirkOSC, écriture manuelle. mode OSC, automation invisible au moment de l'écriture.
- piste 8: Octogris, écriture manuelle. mode Pan Volume, automation invisible au moment de l'écriture.

D'où il ressort que:
- le fait que l'automation soit visible ou non ne change rien à l'affaire
- que la plus grande différence réside entre le mode manuel et le mode automatique.
- qu'en manuel, la précision n'est vraiment pas au rendez-vous dans Logic sauf dans ZirkOSC.
- que SpatGRIS et Octogris se comporte (mal) de la même manière alors que ZirkOSC est beaucoup plus précis.

Il faudrait refaire ces tests et les compléter dans Reaper, Logic et DP.
À vos souris.

![capture d ecran 2016-11-19 a 16 57 53](https://cloud.githubusercontent.com/assets/8959779/20458720/1a9141ac-ae7a-11e6-825d-bd38f0113995.jpg)

**Comment by Xon77** [comment]
Bonjour,
Concernant Reaper, il a quelques réglages concernant l'automation :Comme déjà spécifié dans l'issue 97 d'Octogris, dans les préférences de l'automation de Reaper, l'option "reduce enveloppe point data when recording or drawing automation" permet d'améliorer l'enregistrement et la lecture de l'automation. Et le fait d'avoir un zoom horizontal important pour avoir une grande précision temporelle a aussi une influence sur la précision de l'automation.
Ceci dit, il est clair que l'écriture manuelle est plus imprécise que l'écriture automatique.Je n'ai jamais vraiment testé le joystick, mais je serais curieux de savoir si l'écriture manuelle avec le joystick ou la souris change qqch à l'automation ?

**Comment by Xon77** [comment]
![capture d ecran 2016-11-19 a 17 56 36](https://cloud.githubusercontent.com/assets/1010040/20459447/53b9b454-ae8f-11e6-8480-98eb7dbd9a52.png)

**Comment by Normandeau** [comment]
Testé Reaper 5.28, SaptGRIS 0.18, Comparaison Joystick (en haut)-Souris (en bas)
Une légère différence notable lorsqu'on fait un zoom in, et plus précis que dans Logic.
«reduce envelope point data» était coché sur les deux premières pistes, et décoché sur les suivantes.
Si on regarde en détail l'image, on verra que l'automation est plus précise lorsque la fonction «reduce» est décochée, ce à quoi on s'attend.

![capture d ecran 2016-11-20 a 16 37 29](https://cloud.githubusercontent.com/assets/8959779/20466349/b0a4fba0-af3f-11e6-970b-1a7cf515d4b2.jpg)

**Une remarque importante**: quand on enclenche l'écriture de l'automation, le Movement s'écrit automatiquement et n'est pas très fonctionnel par la suite!

![capture d ecran 2016-11-20 a 16 21 16](https://cloud.githubusercontent.com/assets/8959779/20466466/fa4715d4-af41-11e6-8dce-a185118e79eb.jpg)

Au sujet des Preferences de Reaper:
• Automation transition time 100ms
Specify automation recording return speed: this is the time taken for the envelope to return to its previous value when using actions to write envelope changes.
Cela a surtout à voir avec la façon dont la courbe rejoint les valeurs déjà écrites après Touch.
• Action transition time 100ms
Cette fonction n'est décrite nulle part dans le manuel!

**Comment by vberthiaume** [comment]
Juste à titre de référence, voici les issues précédentes que j'ai trouvé dans spatgris et octogris à propos des automations: 

- https://github.com/GRIS-UdeM/SpatGRIS/issues/25
- https://github.com/GRIS-UdeM/Octogris/issues/114
- https://github.com/GRIS-UdeM/Octogris/issues/91
- https://github.com/GRIS-UdeM/Octogris/issues/59
- https://github.com/GRIS-UdeM/Octogris/issues/37

J'ai pas cherché dans zirkosc parce que spatgris est un descendent direct de octogris ;) 

Mais en gros, oui les automations sont une plaie :)

Pour ce qui est de l'automation du mode de mouvement, effectivement je l'ai fait commencé au début de l'écriture des automations, sinon ça fonctionnait encore plus mal...

**Comment by vberthiaume** [comment]
je viens de remarquer que, sur ma machine du moins, Logic n'utilise que 2 point décimaux pour storer ses automations, par comparaison à 6 décimales pour DP et Reaper ...!!!

**Comment by led78** [comment]
Le problème ne vient pas de la précision décimal de Logic puisque l'écriture d'automation est fluide et suffisamment précise avec ZirkOSC3 (mode manuel). Cependant, lorsqu'on augmente la quantité d'informations envoyées en peu de temps - par exemple, en bougeant rapidement la souris pendant une période de temps, la fan de l'ordinateur (studio hexa) se met à tourner à plein régime alors que le CPU de Logic reste à 0 - l'écriture de l'automation est alors interrompu. Robert mentionnait que cela semblait du à la performance de la ou des cartes graphiques. Après vérifications, il me semble que nous avions conclus que ce problème était lié à la charge de travail supplémentaire que SpatGRIS demandait (en comparaison de ZirkOSC). Après avoir effectué des tests avec la version 1.12, ce problème n'est toujours pas résolu. Il s'agit bien d'un problème de performance et non de précision (Logic).

**Comment by vberthiaume** [comment]
J'ai finalement trouvé le problème. C'est un problème JUCE qu'on peut régler en passant à la dernière version (testé avec 4.3.1). Le problème par contre avec ça est qu'on a besoin de el capitan (ou plus récent) pour compiler (voir #75), et comme hexa est encore (à ce que je sache) sur yosemite, il sera pas mal plus difficile de tester là. Est-ce qu'il est dans les plans d'updater OSX relativement bientôt? Sinon il serait peut-être avantageux pour nous d'avoir une 2e partition avec el capitan, comme jean-michel offrait de faire...

**Comment by vberthiaume** [comment]
les commentaires précédents sont surtout à propos de l'imprécision temporelle. Pour l'imprécision des valeurs comme telles (logic semble fixer la précision des valeurs à seulement 2 décimales), voir ici: 
https://forum.juce.com/t/fix-for-quantization-of-automation-data-by-logic/13736
https://forum.juce.com/t/steppy-automation-recording-on-osx/18308

**Comment by led78** [comment]
J'expérimente le même problème dans DP: plus l'écriture d'automation dure dans le temps, plus le processus surcharge et saute des valeurs dans le temps, ce qui rend l'écriture de l'automation très imprécise. Voici un exemple d'écriture avec une trajectoire de pendule bien simple. On voit que plus le temps avance, plus il manque de valeurs.
![test_gris-udem spatgris_surcharge_automation_dp](https://cloud.githubusercontent.com/assets/13606544/23141883/ee317464-f786-11e6-89e9-e0d6b6d5f1ac.jpg)

**Comment by Normandeau** [comment]
David,
C'est parce que tu utilises des valeurs d'écriture d'automation trop précises. On a déjà répertorié cela: c'était l'Issue no 25.
 Dans DP, il faut aller dans Setup -> Automation Setup et ajustez Min Time et Min Change à des valeurs un peu surprenantes comme ici à 200 ms et 85%. Je viens de faire un pendule de 3 minutes avec deviation et dampening sans problème. Malheureusement les autres séquenceurs n'ont pas ce genre de réglages fins.

![capture d ecran 2017-02-20 a 16 27 24](https://cloud.githubusercontent.com/assets/8959779/23142525/6bcf357a-f78a-11e6-94a4-ddac8815aeb5.jpg)
