### ISSUE TITLE
Coulage audio dans les sorties 1 et 8

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#112]
Dispositif:
- QJackCtl ou JackPilot 64 In-64 Out
- DP ou Reaper 48 Out
- Zirkonium MKII 48 In-10 Out
- Fichiers Octo ou Stéréo
- Dôme de 10 hp: 8 en octo et 2 au plafond
Lorsque je déplace les sources vers le sommet du dôme, il reste toujours de l'audio dans le hp 1 et 8:

En octo, dans DP:
![capture d ecran 2016-11-26 a 16 06 59](https://cloud.githubusercontent.com/assets/8959779/20644316/5834a218-b3fe-11e6-9ab2-6971cf55e683.jpg)

En stéréo dans DP:
![capture d ecran 2016-11-26 a 17 12 06](https://cloud.githubusercontent.com/assets/8959779/20644320/62df367e-b3fe-11e6-9bab-121847e55522.jpg)

Vérification faite avec ZIRKOSC 3.10: même phénomène.

Vérification faite avec Reaper, même chose. On remarquera ici que la différence d'angle des sources 33-34 ne change rien à l'affaire:
![capture d ecran 2016-11-26 a 17 28 23](https://cloud.githubusercontent.com/assets/8959779/20644335/ad82e4e6-b3fe-11e6-9b05-a77b56ee145b.jpg)

![capture d ecran 2016-11-26 a 17 28 43](https://cloud.githubusercontent.com/assets/8959779/20644337/b4a155be-b3fe-11e6-82f6-62fbd242e840.jpg)

Vérification faite avec Zirkonium MKIII, Soundflower et DP: même phénomène...

**Comment by Normandeau** [comment]
Je ne sais pas si c'est relié, mais en testant le même phénomène dans Logic, je constate, qu'en mode de Movements Circular Fully Fixed, en jouant avec la source 1 pendant un certain temps, la source 2 se désynchronise progressivement (il n'y aucune automation enregistrée. Je ne fais que jouer avec la source 1 en mode Read). En complément d'information, ce bogue semble se produire surtout lorsqu'on joue constamment autour du centre du cercle (c'est ce que je teste: pourquoi lorsque les sources dont autour du centre y a-t-il encore du son sur les sorties 1 et 8?):
![capture d ecran 2016-11-27 a 14 05 09](https://cloud.githubusercontent.com/assets/8959779/20651020/d5b8698e-b4aa-11e6-8666-d776a16f9ad4.jpg)

Je confirme que cette désynchronisation se produit aussi avec le mode Circular, Fixed Angle et Fixed Radius. Les angles s'éloignent peu à peu. Symmetric X et Y sont Ok.
Je n'arrive pas à reproduire cela dans Reaper, ni dans DP.

**Comment by Normandeau** [comment]
En refaisant des tests, je confirme que les sources 1 et 8 sont toujours alimentées. Mais je soupçonne que cela est dû à la petitesse de mon dôme, constitué de 10hp seulement (snif...):

![capture d ecran 2016-11-27 a 14 32 53](https://cloud.githubusercontent.com/assets/8959779/20651248/a338391c-b4af-11e6-8853-030b1ab69ade.jpg)

Les HP1 et 8 (flèches) font respectivement partis d'un triangle qui englobe les HP 9 et 10. Ainsi quand je suis au sommet, il est inévitable que le son coule dans les HP 1 et 8. Si mon dôme possédait un niveau intermédiaire, cela se produirait surement aussi, mais avec les hp intermédiaires. À confirmer à la fac.
On a eu cette discussion avec les programmeurs du ZKM. Le défaut principal du VBAP est que le passage d'un triangle à l'autre est une «épreuve» pour le signal. On s'en rend compte lorsqu'on écrit un fichier multiphonique à l'intérieur du Zirkonium, les fondus en entrée et en sortie se font de manière abrupte et non pas lisse.
Plus le dôme est constitué d'un nombre élevé de hp, plus le phénomène de coulage se manifeste dans une zone proche des hp principaux.
Vérification faite avec le dôme 32 de la fac (de manière virtuelle, vive QJackCtl), c'est bien ce que je souçonnais. C'est le VBAP qui «coule».

**Comment by vberthiaume** [comment]
Donc juste pour être certain, le problème ici est que le VBAP n'est pas précis avec les petits dômes? Donc à adresser quand on va choisir l'algorithme pour spatgris server?

**Comment by Normandeau** [comment]
Oui c'est ce que je pense. Mais peut-être aussi que c'est négligeable dans un grand dôme en situation de concert (j'avoue ne pas l'avoir encore remarqué...). Mais dans un petit dôme de composition, on entend parfois le «coulage», selon le type de matériel audio. La question est de savoir est-ce que c'est le VBAP lui-même, ou la version utilisée dans le Zirkonium à l'heure actuelle (version MKII ou MKIII)? À suivre.
