### ISSUE TITLE
Désynchronisation des sources dans Logic

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#114]
En testant le même phénomène de coulage audio dans Logic, je constate, qu'en mode de Movements Circular Fully Fixed, et en jouant avec la source 1 pendant un certain temps, la source 2 se désynchronise progressivement.
Il n'y aucune automation enregistrée. Je ne fais que jouer avec la source 1 en mode Read. 
En complément d'information, ce bogue semble se produire surtout lorsqu'on joue constamment autour du centre du cercle (c'est ce que je teste: pourquoi lorsque les sources dont autour du centre y a-t-il encore du son sur les sorties 1 et 8?):

![capture d ecran 2016-11-27 a 14 05 09](https://cloud.githubusercontent.com/assets/8959779/20651332/5c8a56ce-b4b1-11e6-82e4-776e6170b067.jpg)

Je confirme que cette désynchronisation se produit aussi avec les modes Circular, Fixed Angle et Fixed Radius. Les angles s'éloignent peu à peu. Symmetric X et Y sont Ok.
Je n'arrive pas à reproduire cela ni dans Reaper, ni dans DP.

**Comment by vberthiaume** [comment]
je pense que le problème, à la base, est du à l'imprécision avec laquelle logic gère les automations. Je remarque qu'en mode circular fully fixed (et probablement les autres modes fixed), avec logic il y a un petit "jeu" en bougeant la source sélectionnée. Les sources non sélectionnées ne suivent pas les "petits" mouvements de la source sélectionnée, comme dans ce vidéo:

https://www.dropbox.com/s/482db8g0t984wrc/logic-jeu.mov?dl=0

Et c'est ce qui cause les problèmes quand on arrive au centre, ou il est facile de faire un changement d'angle que les sources non-sélectionnées ne suivront pas. 

Pour contourner le problème, je pourrais forcer un repositionement des sources, selon le mode de movement sélectionné, à chaque fois qu'on en sélectionne une. Le problème avec ça est qu'en écriture d'automation cela créerait des automations pour les sources non-sélectionnées, nous amenant directement dans ce [problème](https://github.com/GRIS-UdeM/SpatGRIS/issues/18)

**Comment by Normandeau** [comment]
Je ne crois pas qu'on devrait modifier SpatGRIS pour que ça marche mieux dans Logic...
Et la solution proposée par Chistophe à l'issue #18 est probablement la meilleure, surtout dans la perspective de l'automation du mode Movements. En effet, si toutes les sources sauf la #1 sont ignorées pendant la lecture de l'automation dans des modes groupés, cela règle deux choses:
- les problèmes de flickering qu'on trouve lorsque la source 2 est écrite alors qu'on est dans un mode groupé. Cela arrive dans Reaper, car celui-ci écrit l'automation trop rapidement lorsqu'on est dans les modes Touch, Latch ou Write;
- cela permet de passer de Independant à l'un des modes groupés ou l'inverse sur la même piste sans créer ce problème, puisque dès que SpatGRIS passerait en mode groupé, les automations écrites pour les sources autres que 2 seraient ignorées.

**Comment by vberthiaume** [comment]
j'ai apporté un fix rapide à l'issue #18, et ne ferai pas de changement ici pour forcer un repositionnement des sources.
