### ISSUE TITLE
Surchauffe des DAWs avec SpatGRIS octophonique

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#116]
Bonjour,
SpatGRIS Audio
Je travaille sur une nouvelle pièce qui n'utilise que des fichiers octophoniques. Et je mets un SpatGRIS 8X8 par piste. Je suis rendu à 7 pistes dans mon projet DP et là, ça chauffe vraiment beaucoup (94% du CPU), et ça finit par générer un message d'avertissement et ça craque pas mal sur le plan audio.
J'ai testé avec DP 9.02 et 9.12, en mode Real-Time et en mode Pre-Gen. Pas de différences significatives. Remarquez Processing et Playback:

![capture d ecran 2016-12-02 a 15 46 38](https://cloud.githubusercontent.com/assets/8959779/20849930/e5ce0e0a-b8a6-11e6-8d49-f3d831b44e7d.jpg)

Je compare avec Logic, même résultat (autour de 85% du CPU) avec un arrêt complet de la session.
Même constat avec Reaper, au-delà de 90% du CPU.

Si j'ouvre la même session avec 7 X Octogris 3.06, je n'arrive qu'à 66% du CPU et ça joue sans problème:

![capture d ecran 2016-12-02 a 15 45 09](https://cloud.githubusercontent.com/assets/8959779/20850026/54fe95ce-b8a7-11e6-917f-ca068560121a.jpg)

Pourquoi une si grande différence entre les deux plugiciels?
7 pistes audio X SpatGRIS Octo = 56 canaux
En comparaison avec SpatGRIS OSC pour la pièce que j'ai jouée à Strasbourg, j'avais:
26 pistes audio X SpatGRIS Stereo OSC = 52 canaux
Mais il est vrai que la spatialisation n'était pas gérée par DP mais par le Zirkonium.

Tests supplémentaires
J'ai augmenté la taille du buffer audio de 512 à 1024 dans les trois logiciels.
DP9, ça règle le problème. Remarquez que Processing  et  Playback sont maintenant très bas, quoique le CPU soit toujours très élevé, à 95% (?!?):

![dp cpu 94 7x8 1024](https://cloud.githubusercontent.com/assets/8959779/20860271/08095b50-b942-11e6-9fda-09073971aea8.jpg)

Comparaison avec Octogis. Pratiquement pas de différence avec le buffer à 512:

![capture d ecran 2016-12-02 a 16 04 03](https://cloud.githubusercontent.com/assets/8959779/20850612/0ad4a576-b8aa-11e6-949b-65bb3fb9f5ea.jpg)

Dans Logic aucun changement et la session s'arrête au bout de 30 secondes environ:

![capture d ecran 2016-12-02 a 16 05 52](https://cloud.githubusercontent.com/assets/8959779/20850627/2371ab92-b8aa-11e6-87ac-49ac33076d15.jpg)

Même chose dans Reaper, ça glitche de partout:

![capture d ecran 2016-12-02 a 16 07 52](https://cloud.githubusercontent.com/assets/8959779/20850644/361cd3ac-b8aa-11e6-9921-9891e2f27452.jpg)

J'ai fait aussi une comparaison avec une session qui date de 2014 où j'ai 19 instances 2X8 de Octogris Joystick, chacune avec une automation.
Voici ce que ça donne:

![capture d ecran 2016-12-02 a 16 21 48](https://cloud.githubusercontent.com/assets/8959779/20850949/b74b4b2e-b8ab-11e6-8bfe-a55fdda94e9f.jpg)

il faudrait aborder cette question, car si j'étais capable il y a 2 ans de travailler avec beaucoup d'instances d'Octogris (mais aussi avant car la session de 2014 date de 2010 à l'origine), il faut aujourd'hui conserver cette flexibilité. Or avec un ordi pas mal plus puissant qu'à l'époque, j'arrive à faire moins. On dirait une publicité pour Apple pour me vendre un nouveau MacBook Pro!

Une idée?

**Comment by Normandeau** [comment]
Je viens de transférer la séquence avec les 19 OctogrisJoystick par des SpatGRIS (merci DP de permettre les substitutions), et voici ce que ça donne. En fait, j'ai plutôt 27 SpatGRIS dans la nouvelle session (j'en ai ajouté): 22 X (2X8) et 5X (8X8). Les 2X8 sont tous automatisés mais pas les 8X8. C'est limite, mais ça joue encore:

![capture d ecran 2016-12-03 a 11 33 50](https://cloud.githubusercontent.com/assets/8959779/20860744/b12d2a4e-b94d-11e6-8ea6-354503a3d7b6.jpg)

Il semble donc que ce sont plutôt les versions 8X8 qui taxent fortement le CPU.

**Comment by Normandeau** [comment]
J'ai encore augmenté la taille du buffer size dans DP à 2048. Voici ce que ça donne, c'est de mieux en mieux. En fait, la session part à 90-95%, puis au bout de quelques secondes, le CPU descend jusqu'à des valeurs autour de 70-80%:

![dp cpu 73 7 x 8 2048](https://cloud.githubusercontent.com/assets/8959779/20869121/bc69db18-ba39-11e6-8b0e-db6c4af63845.jpg)
 
Malheureusement dans Logic, la taille maximale est de 1024 (voir résultat plus haut).
Et dans Reaper même à 2048, la session finit par bloquer et l'audio est très glitchi.

**Comment by vberthiaume** [comment]
Je confirme que les pistes octo bouffent beaucoup de jus, même à l'arrêt dans reaper! Dans mon cas, je n'ai pas de différence entre spatgris et octogris. Les autres?

**Comment by Normandeau** [comment]
Juste pour avoir une idée de comparaison, j'ai placé 64 pistes octophoniques dans une session DP 9.12 et... ça joue!!! (Ça ne joue pas dans DP 9.02. Il faut que je réduise à 56 pistes environ, soit 8 de moins). Ça fait tout de même un total de 64 X 8 = 512 pistes audio! Qui dit mieux? Le buffer est à 2048.

![dp 912 pregen 2048 64 x pistes octo audio](https://cloud.githubusercontent.com/assets/8959779/21233645/e36053aa-c2bd-11e6-8b1c-3c24e7928848.jpg)

En comparaison, je ne peux jouer que 7 pistes octophoniques avec SpatgGRIS avec les mêmes réglages:

![dp 912 pregen 2048 7 x octo audio](https://cloud.githubusercontent.com/assets/8959779/21233846/c607dade-c2be-11e6-999e-aba8cfe927bc.jpg)

Aussitôt que j'ajoute la 8e piste, ça bloque.

**Comment by vberthiaume** [comment]
wow! Avec mon laptop, reaper et un buffer de 1024, j'arrive à peine à faire
jouer une seule piste en 4x4 :).

J'ai fait pas mal de tests à date, et j'ai trouvé que Spatgris est
effectivement plus lent que Octogris. J'investigue pourquoi et comment
améliorer la performance overall!

2016-12-15 12:07 GMT-05:00 Robert Normandeau <notifications@github.com>:

**Comment by Normandeau** [comment]
Je suis en contact régulier ces jours-ci avec MOTU à ce sujet. Curieusement, on arrive à constater que DP902 est plus performant que 912 avec SpatGRIS. Ils continuent à investiguer cela de leur côté.
J'ai poussé l'investigation un peu plus loin, notamment en comparant avec d'autres plugiciels octo. Il n'y en pas des masses qui font du traitement spatial (par opposition au traitement fréquentiel par exemple, moins gourmand). J'ai utilisé GRM SpaceGrain qui fonctionne en mode 8X8. Dans DP 912, j'ai réussi à faire rouler 37 pistes octophoniques avec chacun un SpaceGrain. À partir de 38-39, ça commence à glitcher. Impressionnant!

**Comment by vberthiaume** [comment]
ce problème devrait être amélioré dans la version v0.1.11
