### ISSUE TITLE
Le Span de PanSpan n'est pas indépendant

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#117]
DP9-SpatGRIS 0.19
J'ouvre une instance 2X8 de SpatGRIS et je la mets en Movements Independent et en mode PanSpan.
Je bouge le curseur Pan span et le span de la source 1 bouge.
Je sélectionne la source 2, je bouge le curseur Pan span et c'est toujours le span de la source 1 qui bouge!
Et seulement celui-ci...
Vérification faite avec un fichier  octophonique, même phénomène.
Donc c'est soit la source 1 qui bouge sans la fonction Link, soit c'est toutes les sources avec la fonction Link. Mais il n'y a pas de possibilités de régler des Spans différents d'une source à l'autre sans la fonction Link.
Ouah, ça nous a échappé complètement!

![capture d ecran 2016-12-02 a 17 00 22](https://cloud.githubusercontent.com/assets/8959779/20851862/d81386d2-b8b0-11e6-8fd4-51d0565bb50d.jpg)

Vérification faite: même chose avec Logic et Reaper.

**Comment by vberthiaume** [comment]
wow, beau catch Robert! C'est réglé pour la prochaine version, pour les 3 sliders (surface/distance, azim span et elev span)
