### ISSUE TITLE
Réglette Pan Span inversée

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#119]
Dans Pan Span, la réglette va de la valeur maximum à gauche à la valeur minimum à droite. La logique courante voudrait que ce soit l'inverse: du minimum au maximum.
D'ailleurs, on voit que la logique courante a prévalu pour les deux autres Span — Azimuth et Elevation — car leurs valeurs va de la plus petite à gauche à la plus grande à droite.
Ce serait bien corriger la première afin d'être cohérent avec nous mêmes!

**Comment by vberthiaume** [comment]
facile à régler, mais cela va probablement "briser" les presets précédents...

**Comment by Normandeau** [comment]
Pas certain que ça «brise» grand chose dans la mesure où SpatGRIS n'est pas public.
