### ISSUE TITLE
Rayon: valeur maximale est 2 alors que les séquenceurs écrivent 1

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#121]
Lorsqu'on positionne les Sources ou les Speakers dans leurs onglets respectifs, la valeur maximale du rayon que l'on peut mettre est de 2. Alors que la valeur écrite par les séquenceurs est de 1 (ou de 100 dans le cas de Logic). Une raison à cela?

**Comment by vberthiaume** [comment]
C'est parfaitement normal: tous les paramètres des séquenceurs sont encodés de 0 à 1 (sauf pour les paramètres en échelons, que nous n'avons pas encore implémentés). On réinterprète ces valeurs dans le plugin comme tel, comme par entre 0 et 2 pour le rayon (le rayon est égal à 1 quand les sources sont au niveau des haut-parleurs).
