### ISSUE TITLE
Fermer la fenetre quand la trajectoire roule ne garde pas son etat. 

### ISSUE THREAD

**Issue by theRedMercury** [GRIS-UdeM/SpatGRIS-legacy#127]
Etat de la trajectoire n'est pas sauvegarde
(Attention  : endParamaterGesture)

**Comment by theRedMercury** [comment]
Circular trajectories,  close and open the window lost the sources positions

**Comment by vberthiaume** [comment]
Ce problème est réglé dans logic et reaper: fermer la fenêtre lorsqu'on écrit une trajectoire fonctionne, on finit d'écrire la trajectoire. Par contre lorsqu'on ferme la fenêtre du plugin dans DP, DP ferme tous les composantes de notre plugin (éditeur et processeur), et donc il serait compliqué (utilisation de fichiers) de sauvegarder l'état quand tout est fermé d'un coup. Donc, il serait important d'écrire dans le manuel de ne pas fermer spatgris lorsqu'on écrit une trajectoire avec DP
