### ISSUE TITLE
Développement futur: besoin de spatialiser l'audio dans le séquenceur? Vraiment?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#130]
Dans la perspective où on s'aligne sur le développement d'un logiciel de spatialisation autonome de type Zirkonium, avec des modes de type DBAP, VBAP et Ambisonics HOA, aurons-nous encore besoin d'avoir un plugin qui gère la spatialisation audio dans les séquenceurs? Autrement dit, est-ce que le modèle _The sound of the Mountain_ n'est pas la voie à suivre? Avec un plugiciel de type OSC et un logiciel  de spatialisation externe qui fait du 2D et du 3D.

**Comment by led78** [comment]
aurons-nous encore besoin d'avoir un plugin qui gère la spatialisation audio dans les séquenceurs?

Il me semble que le modèle OctoGRIS - où l’audio est directement géré dans le séquenceur par le plug-in - ne serait plus nécessaire si notre application permet de passer d’un mode de spatialisation à l’autre (sélection entre 2D et 3D), non? Autrement dit, de permettre une panoramisation d’amplitude transparente autant sur un dôme que sur le plan strictement horizontal. Une telle option permettrait d’ailleurs, notamment grâce au DBAP, de briser les règles d’équidistance et du nombre d’haut-parleur si on le désir.
De plus, lorsque je spatialise au dôme, j’aime pouvoir faire des « sauts » d’espace instantanés avec une source, sans devoir parcourir toute la « surface » du dôme. Pour le moment, je dois utiliser deux SpatGRIS, l’un pointé dans une direction, l’autre pointé dans la direction de destination et je fais un jeu de crossfade entre les deux pistes par le biais d’un bus d’envoi. Avec un gros projet comme celui sur lequel je travaille en ce moment, ça devient lourd et difficile à suivre dans le DAW. Ça serait bien d’avoir un bouton du genre « bypass dome » qui serait dynamique et automatisable lorsqu’on utilise une configuration 3D. Commentaires? Objections?

Le 4 févr. 2017 à 12:35, Robert Normandeau <notifications@github.com<mailto:notifications@github.com>> a écrit :


Dans la perspective où on s'aligne sur le développement d'un logiciel de spatialisation autonome de type Zirkonium, avec des modes de type DBAP, VBAP et Ambisonics HOA, aurons-nous encore besoin d'avoir un plugin qui gère la spatialisation audio dans les séquenceurs? Autrement dit, est-ce que le modèle The sound of the Mountain n'est pas la voie à suivre? Avec un plugiciel de type OSC et un logiciel de spatialisation externe qui fait du 2D et du 3D.

**Comment by Normandeau** [comment]
Pour le moment ce qui fait la différence, c'est qu'on a une offre en audio 2D pour Mac et PC et une offre en 3D pour Mac seulement (comme MNTN d'ailleurs). Donc il faudra voir si on développe notre «kit» autant pour l'un que pour l'autre système d'opération.

**Comment by vberthiaume** [comment]
En utilisant JUCE, on peut faire (en principe) des applications mac et
windows sans problème. Il faut simplement limiter l'utilisation de
librairies externe (genre leap, joystick) et/ou faire un installeur sur
windows.

2017-02-04 13:14 GMT-05:00 Robert Normandeau <notifications@github.com>:
