### ISSUE TITLE
Test Comparaison Performance SpatGRIS-MNTN OSC

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#131]
**Test plus détaillés en mode OSC**
MacOS 10.12.3
DP9.12 avec 64 pistes audio mono, session de 7'00
SoundFlower
Agregate Device fabriqué dans Audio-MIDI Setup mais non-utilisé
Zikonium MKII 1.09 ou MNTN 0.8.790/ sur 10HP
SpatGRIS 0.110 ou 0.112/OSC Spatialization

**Zirkonium +0.110**
MKII  avec Meter
CPU total: 74% / Activity Monitor:  DP 480% + MKII 85% + Window Server 20
MKII sans Meter
CPU total: 66% / Activity Monitor:  DP 480% + MKII 30% + Window Server 12
Aucun glitch audio perceptif.

**Zirkonium+0.112**
MKII avec Meter
CPU total: 70% / Activity Monitor:  DP 420% + MKII 85% + Window Server 20
MKII sans Meter
CPU total: 66% / Activity Monitor:  DP 460% + MKII 30% + Window Server 12
Aucun glitch audio perceptif.
Remarque1: DP utilise plus de CPU lorsque les VUMètres du MKII sont inactifs!!!

Léger gain dans DP entre les versions 0.110 et 0.112 en mode OSC

**MNTN**
MNTN + Meter
CPU total: 15% / Activity Monitor:  DP 69% + MNTN 14% + Window Server 12
MNTN  sans Meter
CPU total: 13% / Activity Monitor:  DP 69% + MNTN 6% + Window Server 9
Aucun glitch audio perceptif.

Différence très importante entre MNTN - 15% - et SpatGRIS - 70%.

**Comment by Normandeau** [comment]
Test OSC DP9 + Zirkonium MKII (Meter or not)
SoundFlower 2.02

**Test avec de l'automation (Tunnel Azur)**
Session DP existante avec 48 canaux stéréo = 48 SpatGRIS OSC (2X2), automation écrite sur toutes les pistes.
_DP9.12 + 0.112_ 
- Meter (No Meter)
CPU total: 82% (75%)
Activity Monitor: DP 530% (530%)  MKII 80% (25%) Window Server 30% (25%)

_DP9.12 + 0.110_ 
- Meter (No Meter)
CPU total: 84% (80%)
Activity Monitor: DP 550% (550%)  MKII 70% (25%) Window Server 30% (25%)
Ça glitch avec la version 0.110

**Test sans automation 1 (Anadliad)**
Session DP existante avec 38 canaux: 4XOcto + 3X stéréo, aucune automation.
_DP9.12+ 0.112_
- Meter (No Meter)
CPU total: 42% (34%)
Activity Monitor: DP 200% MKII 65% (25%) Window Server 20% (15%)

_DP9.12+ 0.110_
- Meter (No Meter)
CPU total: 35% (32%)
Activity Monitor: DP 200% (200%) MKII 65% 25%)  Window Server 20% (15%)
Ça glitch avec la version 0.110

**Test sans automation 2 (La part des anges)**
Session DP existante avec 44 canaux: 4XOcto + 6X stéréo, aucune automation.
_DP9.12+0.112_ 
- Meter (No Meter)
CPU total: 65% (60%)
Activity Monitor: DP 320% (320%) MKII 70% (25%) Window Server 20% (15%)

_DP9.12+0.110_
- Meter (No Meter)
CPU total: 60% (55%)
Activity Monitor: DP 300% (320%) MKII 70% (25%) Window Server 20% (15%)
Ça glitch avec la version 0.110

_DP9.02 + 0.112_ 
- Meter (No Meter)
CPU total: 58% (54%)
Activity Monitor: DP 300% (300%) MKII 70% (25%) Window Server 20% (15%)

Remarque: on voit que la principale différence d'activité tient essentiellement dans l'affichage des VUMètres du Zirkonium.
Ce qui m'étonne le plus dans tous ces tests, c'est l'absence de glitchs avec la version 0.112, même sur de longues périodes et avec ou sans agregate device... Mais je n'utilise que 10 haut-parleurs dans ces tests. Il faudrait voir ce que cela donne sur 32 hp par exemple.
Les glitchs sont toujours présents avec le SpatGRIS 0.110.

**Comment by vberthiaume** [comment]
Je suis assez surpris par cette série de tests avec OSC! Il semble que, bien que notre plugin ne fait presque rien en mode osc, il consomme beaucoup plus que le plugin de mountain. Est-ce que ça pourrait être simplement notre interface graphique, plus poussée que celle de mountain?

**Comment by vberthiaume** [comment]
Avec cette configuration:

- Reaper
- 1 piste mono avec spatgris et une autre piste mono avec mntn
- les interfaces des plugins fermées
- le zirkonium et l'app mntn qui roulent dans le background

je n'observe pas de différence de cpu quand je mute/unmute et active/desactive les plugins de chaque piste. 

En d'autres mots, avec des pistes unique qui ne font rien, je ne vois pas de différence dans les performances de nos plugins. Les autres?
