### ISSUE TITLE
Test Mode Audio: BRAVO!

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#132]
MacOS 10.12.3
DP 9.12
SpatGRIS 0.112
Autant de pistes octophoniques que possible

Version 0.110
7 pistes octophoniques

Version 0.112
52 pistes octophoniques!!!

Est-ce que je rêve!!!
Bon c'est clair qu'à ce niveau-là, j'utilise 96% du CPU (Moniteur: 740%) et tous les ventilateurs tournent à fond
Mais tout de même, ça ne glitche même pas!
Reste à tester avec de l'automation...

Bravo les gars, c'est spectaculaire.

**Comment by Normandeau** [comment]
Faudrait tester comparativement avec Logic et Reaper. Et continuer avec DP.
David? Christophe? Vincent?

**Comment by Normandeau** [comment]
**Test avec des versions 2X8 et DP 9.12 sans automation**
0.110
28 pistes seulement pour 97% de CPU
0.112
64 pistes pour 47% de CPU
C'est à se demander s'il reste quelque chose dans le plugiciel!!!

**Comment by Normandeau** [comment]
Test avec des versions 2X8 et **DP 9.12** avec automation, Buffer Size: 1024
Total: 64 pistes pour 52% de CPU
- 16 pistes pour 20% de CPU
- 32 pistes pour 32% de CPU
- 48 pistes pour 41% de CPU
- 64 pistes pour 52% de CPU

Mais ça glitche pas mal, même à 16 pistes.
Aussi: à chaque fois qu'on enregistre de l'automation, il y a toujours une donnée écrite pour Movements, même si on ne l'enregistre pas. 

Test avec des versions 2X8 et **DP 9.02** avec automation Buffer Size: 1024
Total: 64 pistes pour 48% de CPU
- 16 pistes pour 23% de CPU
- 32 pistes pour 30% de CPU
- 48 pistes pour 38% de CPU
- 64 pistes pour 48% de CPU

Ça glitche mais moins qu'avec 9.12, même à 16 pistes.
J'ai testé avec des Buffer Size de 512 et de 1024, et RealTime et PreGen, sans que cela ne change quoi que ce soit.
Donc meilleure performance avec DP 9.02 en mode 2X8. Et moins de glitchs.

**Comment by Normandeau** [comment]
MacOS 10.12.3 DP 9.12
SpatGRIS 0.112 avec automation

48 pistes octophoniques avec automation!!! CPU: 97%
Ça ne semble pas glitcher, mais le matériau est relativement bruiteux.
Je vais essayer avec mon fichier de la mort...

**Comment by Normandeau** [comment]
MacOS 10.12.3 DP 9.12 avec mon fichier de la mort...
SpatGRIS 0.112 avec automation

40 pistes octophoniques avec automation! CPU: 87%
Ça ne semble pas glitcher.
Par contre, je peux forcer et ajouter jusqu'à 8 pistes Octo supplémentaires, mais alors il se produit le phénomène suivant.
Quand le CPU global de mon ordi oscille entre 90 et 100%, bien que la séquence joue, je crois apercevoir que l'automation n'est plus lue par DP ou plus jouée par les SpatGRIS.
Si je prends n'importe quel SpatGRIS par hasard et que je l'ouvre, il n'y pas d'automation qui est lue.
À 40 pistes, soit en bas de 90%, j'ouvre n'importe quelle occurence de SpatGRIS, et l'automation est lue. Ceci est confirmé par les mouvements de VU mètres.
C'est un score assez honorable quand même! Ça fait 40 X 8 = 320 pistes audio.
Pas mal mieux que les 64 de MNTN ou du Zirkonium!!!

Donc le mode 8X8 a un meilleur résultat audio que le mode 2X8 alors que le nombre de canaux audio traités est plus élevé (320 contre 128). Qu'est-ce que ça veut dire?

**Comment by Normandeau** [comment]
Reaper 16 pistes 8X16 avec automation écrite à partir des trajectoires.
43% de CPU total. Activity Monitor: 280%
En ouvrant 8 des 16 fenêtres de SpatGRIS, le CPU augmente à 330%. 
On est surement prêt pour le mode 16X16!!!
Considérant que le mode 8X16 est le plus gourmand.

**Comment by Xon77** [comment]
@Normandeau : Même si l'on n'a pas les mêmes processeurs, avec les nouveaux Mac Book Pro, j'obtiens des résultats de performance assez différents :

MacOS 10.12 / Reaper 5.32 & Block size : 512 / SpatGRIS 0.112 :

Test 8 pistes 8X16 sans lecture automation : 160 % de CPU au total
Test 8 pistes 8X16 avec lecture automation : 195 % de CPU au total

Test 16 pistes 8X16 avec ou sans lecture automation : entre 260 et 280% de CPU au total

A partir de 2 instances du plugin du SpatGris ouvertes, les vumètres et la barre de transport de Reaper commencent à être lus par saccade. Ce phénomène s’aggrave en ouvrant davantage d’instances. Ce qui est très curieux, c’est que l’update des vumètres des plugin est très fluide à la différence de ceux de Reaper.

Le problème principal que je vois pour l'instant, c'est qu'il y a un problème de relecture des automations enregistrées soit en mode manuel ou en écrivant des trajectoires : les automations semblent bien s'enregistrer, mais il y un décalage à le relecture de certaines sources (source sélectionnée) et des comportements illogiques dans la relecture (que, je ne comprends pour l'instant...). Mais, il s'agit d'un nouvel issue...

**Comment by Normandeau** [comment]
J'ai mis à jour les % de CPU pour comparer avec ceux de Christophe. On voit qu'on obtient sensiblement les mêmes résultats avec 16 pistes 8X16 avec automation: 280%.
J'avais écris 43% ce qui correspond à la somme véritable (j'utilise un utilitaire nommé MenuMeters pour cela). Activity monitor liste les % par cœur. 800% correspond à 100% du CPU total pour un 8 cœurs.
J'ai ouvert pour comparaison de l'affichage graphique ma session DP avec 56 pistes octophoniques avec automation (je suis capable d'en lire 40 sur 56) et j'ai ouvert la fenêtre de 16 SpatGRIS. L’affichage de tout — SpatGRIS, VU-mètres, curseur de défilement, compteurs — rame sérieusement, voire est complètement gelé. Mais l'audio a l'air de suivre sans problèmes. Il faudrait valider cela cependant. Isoler une piste, l'écouter attentivement dans le bordel pour vérifier la qualité des trajectoires audio dans des situations de stress intense.

**Comment by vberthiaume** [comment]
Je viens de relire toute cette belle littérature, et, à part les automations qui ne sont plus lues quand on a trop d'instances (probablement le séquenceur qui prends des raccourcis...) le seul (?) problème identifié semble être qu'on a des glitchs en mode 2x8, avec aussi peu que 16 instances de spatgris. Est-ce que c'est exact?
