### ISSUE TITLE
Poignée d'amour dans Reaper?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#136]
Une question: est-ce un bogue de Reaper ou de SpatGRIS ou des deux combinés?

![capture d ecran 2017-02-12 a 16 48 01](https://cloud.githubusercontent.com/assets/8959779/22866339/0fbef83a-f143-11e6-9ae2-38759badb66e.jpg)

On doit toujours saisir la poignée qui nous permet d'agrandir ou de rapetisser la fenêtres de SpatGRIS à deux reprises: la première fois pour modifier la taille du grand carré blanc et la seconde pour le plugiciel lui-même.
À la longue c'est très agaçant. On n'a pas cela dans Logic ou DP.

**Comment by Xon77** [comment]
Cela doit être lié à Reaper, car j'ai le même chose avec le plugin MNTN.Cependant, il doit sûrement y avoir un moyen de régler cela dans Reaper....  

    Le Dimanche 12 février 2017 16h49, Robert Normandeau <notifications@github.com> a écrit :
 

 Une question: est-ce un bogue de Reaper ou de SpatGRIS ou des deux combinés?On doit toujours saisir la poignée qui nous permet d'agrandir ou de rapetisser la fenêtres de SpatGRIS à deux reprises: la première fois pour modifier la taille du grand carré blanc et la seconde pour le plugiciel lui-même.
À la longue c'est très agaçant. On n'a pas cela dans Logic ou DP.—

**Comment by vberthiaume** [comment]
C'est effectivement un truc de reaper, et je n'ai pas trouvé d'option permettant de le mettre à off...
