### ISSUE TITLE
glitches audio en mode 2x8

### ISSUE THREAD

**Issue by vberthiaume** [GRIS-UdeM/SpatGRIS-legacy#137]
voir #132

**Comment by Normandeau** [comment]
(Issue importée de 132)
Test avec des versions 2X8 et DP 9.12 avec automation, Buffer Size: 1024
Total: 64 pistes pour 52% de CPU

    16 pistes pour 20% de CPU
    32 pistes pour 32% de CPU
    48 pistes pour 41% de CPU
    64 pistes pour 52% de CPU

Mais ça glitche pas mal, même à 16 pistes.
Aussi: à chaque fois qu'on enregistre de l'automation, il y a toujours une donnée écrite pour Movements, même si on ne l'enregistre pas.

Test avec des versions 2X8 et DP 9.02 avec automation Buffer Size: 1024
Total: 64 pistes pour 48% de CPU

    16 pistes pour 23% de CPU
    32 pistes pour 30% de CPU
    48 pistes pour 38% de CPU
    64 pistes pour 48% de CPU

Ça glitche mais moins qu'avec 9.12, même à 16 pistes.
J'ai testé avec des Buffer Size de 512 et de 1024, et RealTime et PreGen, sans que cela ne change quoi que ce soit.
Donc légère meilleure performance avec DP 9.02 en mode 2X8. Et un peu moins de glitchs.

Vérification aujourd'hui en modifiant le paramètres Param. Smoothing à 300 ms, mais ça ne change pas grand chose.

**Comment by Normandeau** [comment]
Logic
16 pistes 2X8
Sans automation: CPU: 20%
Avec automation: 23%
Ça glitche un peu également.

Ce serait très important que tout le monde valide ces résultats, avec DP, Logic et Reaper.
Les automations sont des trajectoires automatisées toutes différentes d'une piste à l'autre. Vérifier avec des trajectoires manuelles aussi.
Faire varier le Param. Smoothing dont la valeur maximale a été augmentée à 500 ms. Il semble, d'après mes tests préliminaires, que les glitchs apparaissent à deux occasions assez précises:
- passage au centre (pendulum, spiral)
- trajectoire One Way, lorsque la source revient abruptement à sa position de départ.

J'ai mis les 16 SpatGRIS à 300ms, mais ça ne semble pas changer grand chose, ni dans DP, ni dans Logic.
Faut-il monter à 500ms?

**Comment by vberthiaume** [comment]
Nicolas et moi avons regardé la question, et il semble qu'encore une fois, le problème est qu'on gère mal la spatialization au centre. On peut régler le problème de plusieurs façons: 

1. Mettre un checkbox qui permet d'activer le lissage de volume sur les HP. Cette technique (qu'on utilisait avec la version 0.1.10) prends environ le double du CPU, mais garantie 0 glitchs.
2. Nicolas a eu une idée de quelque chose qui serait assez trivial à faire, qui serait d'enlever complètement le mode pan volume. Le mode pan span avec un span à 0, c'est équivalent, non? Le mode pan est presque aussi rapide que le mode pan volume (avec 32 pistes octo, reaper sur hexa prends environ 620-640% en mode pan volume et 640-680% en pan span) et permet de diminuer vraiment beaucoup la possibilité de glitchs. Par contre il est encore possible, si on se force vraiment beaucoup, d'avoir des glitches.
3. on fait les 2! On enlève le mode pan volume, et permet à l'utilisateur extreme de ne jamais au grand jamais avoir de glitch, au cout d'une forte réduction de performance

**Comment by Normandeau** [comment]
Peut-être la solution PanSpan est pas mal, mais pas dans l'état actuel des choses. J'ai repris la session DP avec 64 pistes 2X8 et j'ai changé le mode Pan Volume par Pan Span avec toutes les valeurs à 0 en mode Link. Malheureusement, la valeur du Span se remet automatiquent au maximum dès qu'on ferme l'interface de SpatGRIS! Étrange non?
L'automation est pourtant en mode Read et aucune automation de PanSpan n'a été enregistrée.
Même comportement dans Logic.
Même comportement dans Reaper: avec une nuance, des fois oui, des fois non!

**Comment by vberthiaume** [comment]
Oui désolé, on a identifié et réglé ce bug de span, et amélioré les
performances pour le prochaine version!

On Feb 18, 2017 16:18, "Robert Normandeau" <notifications@github.com> wrote:

Peut-être la solution PanSpan est pas mal, mais pas dans l'état actuel des
choses. J'ai repris la session DP avec 64 pistes 2X8 et j'ai changé le mode
Pan Volume par Pan Span avec toutes les valeurs à 0 en mode Link.
Malheureusement, la valeur du Span se remet automatiquent au maximum dès
qu'on ferme l'interface de SpatGRIS! Étrange non?
L'automation est pourtant en mode Read et aucune automation de PanSpan n'a
été enregistrée.
Même comportement dans Logic.
Même comportement dans Reaper: avec une nuance, des fois oui, des fois non!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GRIS-UdeM/SpatGRIS/issues/137#issuecomment-280875770>,
or mute the thread
