### ISSUE TITLE
SpatGRIS 0.113 avec Preset ancien plante DP

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#145]
Je suis incapable d'ouvrir la session DP avec les 64 pistes 2X8.
Cela plante DP à tous les coups. Pas le projet lui-même, mais le Chunk avec les 64 pistes.
Rappel: un projet DP peut inclure plusieurs sessions (Chunk).
C'est la session 64 pistes avec autant de 2X8 qui fait problème.
Problème avec le preset?
Je croyais qu'on avait convenu d'une méthode pour éviter cela.
Même situation avec DP 9.02 ou 9.12.

**Comment by theRedMercury** [comment]
Es-tu certain que SpatGRIS n'essaye pas de loader des anciens Presets par défaut ?
On n'est pas sûr qu'il ne plante pas si ce sont des vieux Presets.

**Comment by Normandeau** [comment]
Oui c'est très certainement le cas, mais on s'était justement dit mardi que pour éviter cela, la nouvelle version devait s'ouvrir en ignorant les anciens presets, ou en ouvrant un dialogue permettant de le faire. 
Actuellement ce n'est pas dramatique car le plugiciel n'est pas public, mais il est clair qu'il faut éviter de produire des mises à jour qui plantent les anciennes versions.
Va juste falloir que je me retape la fabrication de séquences 64 pistes...

**Comment by Normandeau** [comment]
Ok, j'ai trouvé une passe-passe. J'ouvre la session DP bloquée mais sans ouvrir SpatGRIS. J'ouvre une nouvelle piste semblable aux autres (genre 2X8), j'y mets un SpatGRIS 0.113 que j'ajuste correctement. Puis grâce à la fonction de DP qui permet de copier un plugin et ses paramètres, j'écrase les SpatGRIS existants dans la session l'un après l'autre. Cela sauve la session.

**Comment by theRedMercury** [comment]
Ok, parfait,

Je crois que j'ai trouvé le problème du mode 12X12 et j'ai rajouté le mode
16X16, mais il faudrait que je le teste avec un fichier de 16 pistes.

Mon mac mini fonctionne parfaitement bien dans l'Hexa.


Le 24 février 2017 à 12:23, Robert Normandeau <notifications@github.com> a
écrit :
