### ISSUE TITLE
Les trajectoires ne fonctionnent plus!?!

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#148]
Ni dans DP, ni dans Reaper, ni dans Logic.

**Comment by Xon77** [comment]
Je crois que c'est lié au fait que la vitesse de la trajectoire est à 0 par défaut, alors qu'elle devrait être à 1

**Comment by Xon77** [comment]
1 est le sens de vitesse de lecture normale
0 arrête le mouvement et le négatif lit dans le sens inverse.
Vore comprtement dans #31

**Comment by Normandeau** [comment]
Bravo, bonne remarque. Donc il faudra que Speed soit ajusté à 1.000 par défaut dans la prochaine version

**Comment by led78** [comment]
Les trajectoires fonctionnent dans Reaper si je change la vitesse de lecture manuellement pour qu'elle soit autre que 0. Dans Logic toutefois, les trajectoires ne fonctionnent tout simplement plus, quelle que soit la vitesse de lecture.

**Comment by led78** [comment]
Voici une petite vidéo du problème que je rencontre: https://www.dropbox.com/s/g9kw5fag56nw6wr/Tests_SpatGRIS_0.1.13_Trajectoires.mov?dl=0
