### ISSUE TITLE
Clic audio lors de la modification du Volume speakers (dB) dans l'onglet Volume & Filters

### ISSUE THREAD

**Issue by Xon77** [GRIS-UdeM/SpatGRIS-legacy#150]
MacOS 10.12.3
Reaper 5.32
SpatGRIS 0.113

et éventuellement d'autres sliders comme Filters speakers

**Comment by Xon77** [comment]
Des clics se produisent lors de la modification de 2 principaux paramètres dans l'onglet Volume & Filters :    
- Volume center (dB)
- Volume speakers (dB)

A noter aussi que : 
- le toggle "Apply Filter" génère un clic lors de son activation / désactivation (ce qui n'est pas important, mais serait préférable d'éviter pour une cosmétique sonore),
- et que son automation n'est pas enregistrée, puisque c'est un paramètre discret.

**Comment by theRedMercury** [comment]
Je peux supprimer les clics audio quand on change les volumes grâce au OUTPUT_RAMPING mais cela fait baisser énormément les performances du SpatGRIS.

Je vais essayer de le rendre activable ou non via l'interface graphique.
Cela ne résoudra pas le clic de "Apply Filter".

**Comment by Xon77** [comment]
Est ce que les performances CPU sont affectés uniquement lors du changement de ces sliders Volume ou dans toutes les situations, peu importe si ces sliders de volume sont bougés ? 

    Le Mardi 28 février 2017 11h34, Nicolas M. <notifications@github.com> a écrit :
 

 Je peux supprimer les clics audio quand on change les volumes grâce au OUTPUT_RAMPING mais cela fait baisser énormément les performances du SpatGRIS.Je vais essayer de le rendre activable ou non via l'interface graphique.
Cela ne résoudra pas le clic de "Apply Filter".—

**Comment by theRedMercury** [comment]
Si OUTPUT_RAMPING  est activé, les performances CPU seront affectées en permanence.

**Comment by Xon77** [comment]
As tu par hasard une idée de l'ampleur de l'impact CPU ? le double ?

De manière similaire à l'issue #47 , avec le problème de clic au croisement du centre, qui obligeait une couche de lissage supplémentaire et donc une augmentation de CPU, il va falloir faire un compromis entre lissage et absence de clic vs très bonnes performances CPU avec de nombreuses pistes. Et aussi savoir quels sont les paramètres, dont le clic peut être acceptable car il n'est pas sensé être modifié au cours de la séquence, pièce...

**Comment by theRedMercury** [comment]
Le double facilement, c'est exponentiel en fonction du nombre de speakers. En 2x2 on ne verra pas trop de différence, mais en 8x16 c'est une autre histoire.

**Comment by Xon77** [comment]
Est ce que l'issue #146 peut être réglé avec le même type de lissage ?
Peut-être ressortir une version intégrant ces corrections de clic et retester les performances et le nb de pistes simultanées ? mais je crains que l'on revienne à un problème de performance CPU, que l'on rencontrait avant...

**Comment by theRedMercury** [comment]
Oui cela réglera le problème #146

**Comment by Xon77** [comment]
Cela serait super si tu pouvais rendre le lissage activable ou non via l'interface graphique. Cela nous permettrait de faire facilement des tests. @Normandeau ?
Ils règleraient de manière relative (via un toggle dans l'interface graphique) cet issue et #146 .
Est ce que tu crois que l'issue #47 peut aussi être réglé de la même façon ? ou alors c'est encore une autre histoire...

**Comment by theRedMercury** [comment]
Je viens de rajouter ce fameux bouton toggle, et normalement ça devrait aider pour l'issu #47.

Mais attention aux performances, je dois encore voir si il y moyen d'optimiser cela un peu, car en 8x16 je n'arrive pas à lire correctement un fichier 8 pistes avec le lissage activé.

**Comment by Normandeau** [comment]
Feu rouge ici.
Toute cette discussion est très bien, mais ne concerne qu'un cas extrêmement spécifique d'un problème qui n'est pratiquement pas rencontré par les utilisateurs. En effet, le fait que les Volume et les Filters cliquent est selon moi un problème secondaire dans la mesure où les plupart des gens ne vont faire des ajustements ici qu'une seule fois, au début de leur session. On n'a jamais testé ces paramètres en situation d'automation, et personne n'a jamais mentionné que cela leur causait un problème. Donc on met cela dans la whish list et on ne travaille plus là-dessus pour le moment. Il y a pas mal ce choses à corriger en ce moment sans celui-ci. Et surtout on ne va toucher aux performances tant que le reste n'est pas réglé.
