### ISSUE TITLE
PanSpan avec 0.113: encore plus de pistes

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#152]
MacOS 10.12.3
DP 9.12 avec un buffer de 1024
SpatGRIS 0.113 Mode PanSpan
Autant de pistes octophoniques que possible

Version 0.110
7 pistes octophoniques

Version 0.113
60 pistes octophoniques avec automation!!!

Bon c'est clair qu'à ce niveau-là, j'utilise autour de 90% du CPU global (Moniteur d'activité: 700% pour DP) et tous les ventilateurs tournent à fond. Et DP me lance parfois son message d'avertissement, ce qui a pour conséquence d'arrêter la lecture de l'automation de certains SpatGRIS, mais pas tous.
Mais tout de même, ça ne glitche même pas!
Ça fait tout de même 480 pistes audio!!!

Bravo, c'est spectaculaire comme amélioration.

**Comment by theRedMercury** [comment]
![image](https://cloud.githubusercontent.com/assets/6116482/23371111/04fc5e94-fce5-11e6-8abe-79c97b0159c2.png)


Voici la nouvelle interface graphique pour SpatGRIS version 0.2

**Comment by Xon77** [comment]
Merci, @theRedMercury pour ta rapidité!

Tests : MacOS 10.12.3 / Reaper 5.32 & Block size : 512 / SpatGRIS 0.2 :

Test 1 piste 8X16 avec lecture automation : 50 % de CPU au total
Test 1 piste 8X16 avec lecture automation & Ramping lissage : 120 % de CPU au total

Test 2 pistes 8X16 avec lecture automation : 90 % de CPU au total
Test 2 pistes 8X16 avec lecture automation & Ramping lissage : 230 % de CPU au total

Test 3 pistes 8X16 avec lecture automation : 120 % de CPU au total
Test 3 pistes 8X16 avec lecture automation & Ramping lissage : 350 % de CPU au total

Test 8 pistes 8X16 avec lecture automation : 210 % de CPU au total
Test 16 pistes 8X16 avec lecture automation : 330 % de CPU au total, mais les vumètres et la barre de lecture comment à ramer et bougent par saccade, mais le son a l'air OK, pour l'instant. 300 %, si les interfaces graphiques sont fermées.

Pour comparaison avec la version SpatGris 0.112 : 
Test 8 pistes 8X16 avec lecture automation : 195 % de CPU au total
Test 16 pistes 8X16 avec lecture automation :  280% de CPU au total

Bien qu'il soit particulièrement gourmand, l'option Output Raming permet d'éliminer les clics, qui sont les plus critiques (ou pas), notamment ceux au croisement du centre, mais aussi celui de l'ouverture du PanSpan : seulement au changement de Pan Span de 0 vers une autre valeur, j'entends un petit clic... Il disparait avec l'output Ramping. J'ouvre une nouvel issue ?

**Comment by theRedMercury** [comment]
Non, pour le moment on va garder cette option avec le Output Ramping, dans le futur il faudra trouver un moyen plus économique que celui-ci pour éviter les clics.

**Comment by Normandeau** [comment]
Si je comprends bien tes tests Christophe, toutes ces trajectoires sont en temps réel n'est-ce pas? C'est bien de faire ces tests, car cela nous permet de tester la robustesse du plugiciel. Mais la fonction des trajectoires n'en est pas une de temps réel, mais d'écriture. Donc on conçoit une trajectoire, et lorsque celle-ci est à point, on l'écrit. Après, le séquenceur se contentera de la lire, ce qui est beaucoup plus économique en terme de CPU. Donc si la fonction Output Ramping fait le travail en mode d'écriture, même si c'est plus gourmand, c'est le résultat sonore que l'on cherche. Ce qu'il faut valider ici cependant, c'est le résultat sonore en lecture d'automation. Doit-on laisser la fonction Output Ramping active? Ou celle-ci n'est-elle nécessaire qu'en mode d'écriture?

**Comment by Xon77** [comment]
Ces tests ont été faits avec une lecture d'automation préalablement écrite avec des trajectoires, comme tu le fais. Je ne teste pas le CPU sur l'écriture des trajectoires. Le résultat sonore a l'air OK pour l'instant... mais je n'ai testé qu'avec mon portable...
La fonction output ramping est trop gourmand pour être utilisable pratiquement, mais est utile pour faire des tests et évaluer et éviter si nécessaire les clics...
La fonction output ramping n'est absolument pas nécessaire en mode écriture...

**Comment by Normandeau** [comment]
Puisque le Output Ramping a été enlevé avec la version 0.200, je ferme cette issue.
