### ISSUE TITLE
DP Buffer size Incorrect

### ISSUE THREAD

**Issue by theRedMercury** [GRIS-UdeM/SpatGRIS-legacy#153]
![screen shot 2017-02-27 at 15 05 42](https://cloud.githubusercontent.com/assets/6116482/23377595/9c32192a-fcfe-11e6-80ab-03cdd0e82f16.png)

Attention dans DP, le plugin croit qu'il travaille à 2048 mais en réalité DP est à 512.
Cela fait planter DP quand on est en mode 12X12 ou 16X16.

**Comment by led78** [comment]
Les trajectoires fonctionnent dans Reaper si l’on change manuellement la vitesse de lecture pour qu'elle soit autre que 0.

Dans Logic (version 10.3.1) toutefois, les trajectoires ne fonctionnent tout simplement plus et ce quelle que soit la vitesse de lecture.

**Comment by theRedMercury** [comment]
J'ai désactivé l'automation de la vitesse, donc cela ne devrait ne plus posé de problèmes pour la suite.

**Comment by Normandeau** [comment]
Les modes 1X12 et 2X12 fonctionnent sans problème dans DP.
Le mode 12X12 ne fonctionne pas dans DP, bien qu'il soit possible de l'ouvrir.
Voici à quoi il ressemble:

![12x12 dp](https://cloud.githubusercontent.com/assets/8959779/23380442/caaa0f74-fd08-11e6-8919-c81b502f7da1.jpg)

Tout est figé. Le Span ne fonctionne pas. Les Sources et les Speakers n'apparaissent pas. Et il n'y a pas d'audio.
Très rapidement la session finit par planter DP et alors il n'y a plus rien à faire, il faut effacer la piste sur laquelle on a mis un SpatGRIS 12X12. Même en testant différents Buffer Size et en revenant à 2048 (ce qui est très inhabituel dans des modes de fonctionnement normaux. J'utilise toujours 1024, voir 512 en situation de concert).
Dans DP, on ne peut pas faire de mixage complexe: par exemple on ne peut pas faire de combinaisons comme 4X6, ou 4X8 ou 4X12. Ainsi ici, on ne peut pas faire de 4X12, de 6X12 ou de 8X12, ce qui serait parfois utile. C'est une limite de DP.

**Reaper**
Tous les modes X12 fonctionnent dans Reaper, sauf 12X12, qui se comporte exactement comme dans DP: tout est figé.

Quant au mode 16X16, il n'est tout simplement pas implémenté encore. Il sera incompatible avec tous les séquenceurs audio, sauf Reaper.

**Comment by Normandeau** [comment]
J'ai mis un nouveau dossier dans le DropBox avec trois fichiers de numéros décalés: 8p, 12p et 16p. Avec ma jolie voix dont vous ne pourrez plus vous passer. Très utile pour faire du déboguage:
https://www.dropbox.com/s/hl3wvij1i9qk9dp/Fichiers%208%2C%2012%20et%2016.zip?dl=0

**Comment by theRedMercury** [comment]
https://forum.juce.com/t/resolved-issue-for-more-than-8-channels/19993/12

**Comment by Normandeau** [comment]
Hormis la discussion au sujet du mode 12X12, retiré de la version 0.200, je ne comprends pas l'issue d'origine. Comment le plugin peut-il fonctionner à une valeur de buffer autre que celle déterminée par le séquenceur?
