### ISSUE TITLE
DP crash avec 0.200

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#156]
Crash
Plusieurs Crash de DP à l’ouverture de la session 64X2X8
Est-ce que c’est relié à la régence de presets, pourtant enregistrés avec la version 0.113?
J’ai remis celui-ci, enregistré de nouveaux presets.
Fermer la session, remplacé la version 0.113 par la 0.200.
Dans l’intervalle j’ai remplacé deux instances de SpatGRIS (les pistes 1 et 2 sur 64) qui contenait des presets.
Réouvert la session: pas de problème… puis deuxième glitch numéique.
On arrête tout.

J’ai aussi un autre type de crash à répétition.
Je "duplicate" une séquence sur laquelle je viens de travailler, puis j’essaie d’ouvrir la copie, et boum, ça crash.
Je viens de trouver: si un SpatGRIS est laissé ouvert dans une séquence, soit celle que l’on quitte ou celle que l’on veut ouvrir, cela crash DP.
À la réouverture, lorsque j’essaie d’ouvrir un SpatGRIS, cela crash presqu’à tous les coups.
Évidemment on ne peut pas comparer avec Reaper ou Logic, car DP est le seul à offrir le concept de container avec plusieurs séquences dans le même projet.

Bruit numérique
J’ai eu aussi un énorme bruit numérique à l’ouverture d’une des instances de SpatGRIS. J’ai dû fermer tout le système d’urgence (il n’y a pas de Mute ici…) mais avant j’ai pu apercevoir que cela s’accompagnait sur le plan visuel avec un comeback d’une situation ancienne: tous les éléments du plugiciel se sont retrouvés dans le bas à gauche.
Le buffer de DP était à 2048. Je l’ai descendu à 1024, réouvert la session et joué avec et depuis je n’ai pas eu le problème.

J'envoie par courriel le CrashReport de DP (Github ne suporte pas le format .diag

**Comment by Normandeau** [comment]
J'ai remis la version 0.113 et rien ne va plus. DP crash maintenant systématiquement. Et je ne peux rien vérifier car aussi tôt que j'essaie d'ouvrir soit une nouvelle session, soit une instance de Spatgris, ou soit j’appuie sur Play, boum, ça crash.

**Comment by theRedMercury** [comment]
Je pense qu'il s'agit de ton projet DP qui est corrompu ou quelque chose du genre.

Je viens d'avoir quelque chose de très bizarre avec ton projet DP que tu m'as envoyé via DropBox.

Quand j'ouvre ton projet, je n'arrive pas à ouvrir les SpatGRIS qui se trouvent sur les pistes existantes.
Ce n'est pas encore trop grave, je supprime le SpatGRIS des effets de la piste et j'en rajoute un nouveau.
Dans ton projet j'ai rajouté une piste à moi avec le même fichier audio. Je rajoute aussi un SpatGRIS sur cette nouvelle piste.

J'ai fait tourner sur 4 SpatGRIS une automation en même temps pendant 2min, cela à fonctionné parfaitement.

J'ai sauvegardé, j'ai quitté DP, j'ai tout relancé et tous fonctionnaient très bien.
J'ai éteint mon Mac mini, et quand j'ai voulu rouvrir ton projet avec ma piste à moi. 

Je n'arrivais plus à ouvrir les SpatGRIS sur Tes Pistes, mais j'arrivais à ouvrir seulement celui qui se trouve sur Ma Piste...


C'est quelque chose de très étrange, mais je pense que DP doit cacher des choses sur la gestion des Plugin.

**Comment by Normandeau** [comment]
Cela a l'air d'aller avec la nouvelle version. J'ai refait deux nouvelles sessions complètes avec des instances 2X8 et des 8X8, afin d'éviter de traîner des bogues d'une session à l'autre. Ça tient la route. Aucun crash de la journée, peu importe les opérations. Ouf!
pour l'instant je débranche la sono et j'écoute sur les hp du Mac... Quand je serai certain de la solidité, je me remettrai à l'écoute.

**Comment by Normandeau** [comment]
J,ai fait toute une série de tests aujourd'hui avec le mode OSC. Tout a l'air d'aller. Je ferme cette issue.
