### ISSUE TITLE
Version 0.200 Performance et Améliorations

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#157]
**Performance**
56X8X8 avec automation: 
CPU Général:  entre 85 et 90% (donc à la limite)
DP 9.12 (buffer: 1024): entre 630 et 700%
Ça travaille fort mais ça tient.
56 pistes Octo avec automation dont 10 instances ouvertes
Avec cette intensité de tâche j’obtiens presque toujours le message d’alerte de DP. Lorsque cela arrive, quelques-uns des SpatGRIS ouverts, mais pas tous, arrêtent de fonctionner (je ne sais pas pour ceux qui sont fermés). J’arrête la session et je démarre. De temps en temps, je n’ai pas le message d’alerte. Quand c’est le cas, la session roule sans problème.

Aucune différence notable entre une session avec les 10 SpatGRIS ouverts ou tous fermés.
Il faut que je descende à 52 pistes octo avec automation pour ne pas avoir le message d’alerte.
CPU Général:  entre 75 et 79 %
DP 9.12: 590%
C"est quand même remarquable.

**Améliorations**
Presets
Je remarque que (presque) tous les paramètres de SpatGRIS font maintenant partie des Presets, y compris la position absolue des Sources.
C’est excellent.

Sauf le Input/Output Mode
Comme celui-ci ne se règle plus automatiquement dans DP et Logic, ce serait bien de l’ajouter dans la liste des paramètres que le preset conserve.

À corriger:
Speakers
C’est bien de mettre les valeurs de Ray (0-2) entre parenthèses, sauf que ce n’est vrai qu’en mode FreeVolume. Pour PanSpan, la plage de valeurs est située entre 0 et 1.

Trajectories
Interface graphique
- Ellipse: width factor est incomplet (width fact…)
- Pendulum: dampening est incomplet (dampenin…)
- Random: Force separate automation est incomplet (Force separate automati…)

**Comment by Xon77** [comment]
Juste un petit commentaire sur la valeur de Ray (0-2) des Speakers entre parenthèses : Pour PanSpan, la plage de valeurs est fixe (pas situé entre 0 et 1) et n'est pas modifiable à la différence de FreeVolume.

**Comment by Normandeau** [comment]
Version 0.200 (17-03-03)
Performance
48X8X8 avec automation:
CPU Général: entre 75 et 80%
DP 9.12 (buffer: 1024): entre 600 et 675%
Ça travaille fort mais ça tient.
Au-delà, ce n'est pas vraiment fiable, notamment sur le plan de la lecture de l'automation.
Aucune différence notable entre une session avec 10 SpatGRIS ouverts ou tous fermés.
C'est quand même remarquable.

Input/Output Mode dans les Presets
C'est corrigé.

Speakers
C’est bien de mettre les valeurs de Ray (0-2) entre parenthèses, sauf que ce n’est vrai qu’en mode FreeVolume. Pour PanSpan, la valeur est située à 1 (merci Christophe).
Corrigé

Trajectories
Interface graphique
Corrigé
