### ISSUE TITLE
Free Drawing

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#162]
Bravo, excellent ajout. 
Une question cependant: quelle est la relation entre la durée de la trajectoire écrite et la durée de la trajectoire lue?
Un exemple: j'enregistre une trajectoire FreeDrawing pendant 10 secondes. Puis je la rejoue en Mode OneWay. Au lieu de jouer la trajectoire écrite pendant la durée originelle, soit 10 secondes, il joue la trajectoire systématiquement 3 fois. Donc la trajectoire originelle est jouée à 3 fois la vitesse originelle. Pourquoi ce rapport?
Si le la joue en mode Return, il la joue une fois et demie, ce qui correspond aussi à 3 fois la vitesse.
Ok, je viens de comprendre, la vitesse de l'écriture et celle de la lecture n'ont rien à voir. La vitesse de la lecture correspond à celle indiquée dans la trajectoire. Dans mon cas, la durée était de 5 secondes et était réglée à 3 cycles, soit 15 secondes. Donc la trajectoire écrite est lue en fonction de cela, soit à la vitesse de 5 secondes, trois fois. 
Bon à savoir pour le manuel!!!

**Comment by led78** [comment]
Il faudrait ajouter une commande permettant d'effacer une trajectoire dessiner (mode Free Drawing) autrement qu'en supprimant l'insertion de SpatGris complètement. Ça peut devenir assez encombrant visuellement et lourd à supporter graphiquement que d'avoir un spaghetti de trajectoires accumulées.

**Comment by Xon77** [comment]
Comme signalé par Nicolas dans le courriel du dernier release, la trajectoire Free Drawing s'efface avec un clic droit. 

    Le Lundi 3 avril 2017 23h32, David Ledoux <notifications@github.com> a écrit :
 

 Il faudrait ajouter une commande permettant d'effacer une trajectoire dessiner (mode Free Drawing) autrement qu'en supprimant l'insertion de SpatGris complètement. Ça peut devenir assez encombrant visuellement et lourd à supporter graphiquement que d'avoir un spaghetti de trajectoires accumulées.—
