### ISSUE TITLE
Variation incohérente du Speed dans 0.2.2

### ISSUE THREAD

**Issue by VinyMo** [GRIS-UdeM/SpatGRIS-legacy#164]
Dp 9.12_Buffer size 2048 - SpatGRIS version 0.2.2
En mode 2X8 - source 1 ou 2 maîtresse (le problème apparait dans les 2 cas)- free volume ou pan span (même chose, le problème apparaît dans les 2 cas), trajectoire pendule: symétrique y, lors du jeu sur le speed avec la division temporelle suivant les "beat" et en forçant un ratio favorisant le déroulement rapide de la séquence en fonction d'une valeur équivalente par exemple à la ronde à 120 avec 1 beat par cycle, lorsque je joue avec le speed, de 0 à 1.0  il y a effectivement une accélération puis de 1.0 à 2.0 on obtient une progressive décélération avec un ralentissement clairement audible à 2.0, et ensuite de 2.0 à 2.5 accélération à nouveau. Le graphique de l'interface suit un peu plus difficilement les très grandes vitesses de mouvements mais arrivé à 2.0, ça ralenti clairement.

**Comment by VinyMo** [comment]
J'ai oublié de mentionner, je suis sur OSX 10.9.5 (Mavericks)

**Comment by VinyMo** [comment]
Désolé, fermé l'issue par erreur.

**Comment by Normandeau** [comment]
J'ai essayé de reproduire ce problème, mais je n'y arrive pas, Nicolas non plus. Il doit nous manquer une donnée pour la reproduction. J'utilise DP 9.13 et un buffer size de 1048, mais je ne crois pas que ça soit significatif.
J'ai enregistré deux courbes de pendulum, la première avec une précision d'écriture moindre (100ms à 85%) que la seconde (10ms à 25%). On voit clairement les courbes accélération/ralentissement (Speed qui varie de 0à 2,5 et ensuite de 0 à -2,5).
Je crois que ce qui est en cause c'est la vitesse. Avec une valeur de ronde à 120 (c'est la valeur que tu spécifies), la vitesse de départ est déjà très élevée, équivalente à noire à 480, ce qui est au-delà de la limite du séquenceur (noire à 400). Donc quand tu accélères, c'est tout simplement trop vite et tout se dérègle.
Ici j'ai fait l'enregistrement à noire à 60.

![capture d ecran 2017-05-21 a 11 08 11](https://cloud.githubusercontent.com/assets/8959779/26285086/3b237f6c-3e16-11e7-91cd-dfde400150cd.jpg)

**Comment by VinyMo** [comment]
Lorsque tu dis la limite du séquenceur est la noire à 400, moi ce que je vois c’est que la boîte à chiffre se rend à 400 aussi bien pour la ronde que pour la noire…Je suis sur Dp 9.12 mais peu pas être ça. Je refais le même processus et à chaque fois c’est la même chose, en mode latch, touch et pour toutes les trajectoires sauf la spirale qui colle sur le cadre très rapidement.

Je remarque d’autre part que le nombre de paliers accélération/ralentissement est fonction du nombre de beats par cycle; si je mets .5 beat par cycle, les paliers sont à chaque fraction équivalente à .5

0. à .5 accélère, .5 à 1.0 décélère, 1.0 à 1.5 accélère etc…Alors qu’avec 1 beat par cycle on obtenait les résultats que j’ai postés, 0. à 1.0 accélère, 1.0 à 2.0 décélère, 2.0 à 2.5 accélère...
On May 21, 2017, at 11:22, Robert Normandeau <notifications@github.com<mailto:notifications@github.com>> wrote:


J'ai essayé de reproduire ce problème, mais je n'y arrive pas, Nicolas non plus. Il doit nous manquer une donnée pour la reproduction. J'utilise DP 9.13 et un buffer size de 1048, mais je ne crois pas que ça soit significatif.
J'ai enregistré deux courbes de pendulum, la première avec une précision d'écriture moindre (100ms à 85%) que la seconde (10ms à 25%). On voit clairement les courbes accélération/ralentissement (Speed qui varie de 0à 2,5 et ensuite de 0 à -2,5).
Je crois que ce qui est en cause c'est la vitesse. Avec une valeur de ronde à 120 (c'est la valeur que tu spécifies), la vitesse de départ est déjà très élevée, équivalente à noire à 480, ce qui est au-delà de la limite du séquenceur (noire à 400). Donc quand tu accélères, c'est tout simplement trop vite et tout se dérègle.
Ici j'ai fait l'enregistrement à noire à 60.

[capture d ecran 2017-05-21 a 11 08 11]<https://cloud.githubusercontent.com/assets/8959779/26285086/3b237f6c-3e16-11e7-91cd-dfde400150cd.jpg>
