### ISSUE TITLE
Alt-Clic sur Speed génère un full Span!!! SpatGRIS 1.0

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#165]
Si on Alt-clique (ou Option-clic) sur le curseur de Speed, cela génère un full Span!?!
J'ai trouvé cel en me demandant s'il y avait une fonction de remise à 0 de ce paramètre — Speed — en alt-cliquant dessus!

![alt-clic full-span](https://cloud.githubusercontent.com/assets/8959779/26277706/47fe9390-3d5b-11e7-93bd-7280e81d4592.jpg)

**Comment by theRedMercury** [comment]
Oui, mince, c'est vrai, c'est quelque chose que j'avais réglé dans les
versions suivante.

Je peux le modifier lundi et remplacer la version sur git hub.

Désolé.

Nicolas.

**Comment by led78** [comment]
Le problème semble maintenant réglé, du moins dans Logic. Peut-on fermer cet issue? 
Lorsque j'appuie sur Alt+clic, ça remet le curseur à sa position par défaut, en l'occurence une vitesse de 1.0 pour le paramètre « speed », 50 ms pour le paramètre de « smoothing », etc.
