### ISSUE TITLE
Version 1.0 (anciennement 0.2): performance et comparaison avec 0.2.1

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS-legacy#166]
**Test SpatGris 2.1 - Logic Pro X**
Spécificités techniques:
**Ordinateur**
Modèle: Mac Pro (Fin 2013)
Processeur: 3 GHz 8-Core Intel Xeon E5
Mémoire: 32 Go 1866 MHz DDR3
Graphisme: AMD FirePro D700 6144 Mo
Système: macOS Sierra 10.12.4
**Séquenceur**
Logic Pro X 10.3.1
Fréquence d’échantillonnage: 48kHz
Taille du buffer E/S (par défaut): 512 échantillons
************************************************************************************************
**Test de performance 1.1**
Nombre de piste: 64
Type de piste: 8 canaux (7.1; 3/4.1)
Automations: Oui, sur chaque piste (Source 1 X; Source 1 Y); tous en mode lecture; écrites à partir du mode « Random », donc très dense et saccadée.
Plugiciel: **SpatGRIS 0.2.1** en mode 8X8; toutes les trajectoires sont des mouvements groupés.
**Résultats:**
- CPU général: autour de 40% (pointe à 50%)
- % Processeur: entre 630 et 750%; généralement autour de 650% avec pointes à 750%)
- Aucune différence de CPU et du % Processeur avec 10 instances du plugiciel ouvertes, mise à part un taux de rafraîchissement visuel nettement plus lent.

**Test de performance 1.2**
Nombre de piste: 72 (+ 8 piste octophoniques [8X8] par rapport au test 1.1)
**Résultats: Peu de changement au niveau du CPU général.**
- CPU général: + 2% en moyenne (autour de 42%)
- % Processeur: + 50 % en moyenne; entre 670% et 800%; généralement autour de 700% avec pointe à 830%!

**Test de performance 1.3**
Nombre de piste: 80 (+ 8 piste octophoniques [8X8] > test 1.2; + 16 > test 1.1)
**Résultats: % Processeur pratiquement inchangé (diminué même!), mais CPU général augmenté.**
- CPU général: entre 42 et 48% (pointe à 55%)
- % Processeur: entre 665 et 765%; généralement autour de 700% avec pointes à 800%.

**Test de performance 1.4**
Nombre de piste: 96 (+ 16 piste octophoniques [8X8] > test 1.3; + 32 > test 1.1)
**Résultats: Nette augmentation du CPU et du % Processeur.**
- CPU général: entre 50 et 60% (pointe à 65%)
- % Processeur: entre 830 et 930%; généralement autour de 850% avec pointes à 1035%!
- Aucun message d’erreur, ni de signes de fatigue; ça roule sans problème et je n’entend pas la ventilation du Mac Pro; mais le moteur audio est à fond.

**Test de performance 1.5**
Nombre de piste: 128 (+ 32 piste octophoniques [8X8] > test 1.4; + 64 > test 1.1)
**Résultats: premier message de surcharge du moteur audio! (taille du buffer: 512)**
- Taille du buffer ajustée à 1024: même résultat, je n’ai pas le choix de supprimer des pistes, sans quoi le moteur audio ne parvient à sortir aucun son. 
- Il est difficile d’aller au-delà de 96 pistes sans être interrompu par une surcharge.

**Test de perfromance 2.1**
Taille du buffer E/S: 1024 échantillons
Nombre de piste: 96
Type de piste: 8 canaux (7.1; 3/4.1)
Automations: Oui, sur chaque piste (Source 1 X; Source 1 Y); tous en mode lecture; écrites à partir du mode « Random », donc très dense et saccadée.
Plugiciel: **SpatGRIS 1.0 (official release; anciennement 0.2)** en mode 8X8; toutes les trajectoires sont des mouvements groupés.
**Résultats: la version 1.0 semble en demander légèrement plus au processeur que la version 0.2.1**
- CPU général: entre 50 et 60% (pointe à 65%)
- % Processeur: entre 840 et 1000%; généralement autour de 900% avec pointes à 1040,5%!
- Le moteur audio fonctionne à pleine capacité comme jamais. Tout est au planché.
![capture de test_performance_01](https://cloud.githubusercontent.com/assets/13606544/26421907/b2ae4a9a-4095-11e7-98fb-ce14e5ccaf5b.jpeg)
- Aucun message de surcharge cependant. Tout roule sans problème.

Note: les pourcentages sont le résultat d’un suivi visuel des variations de % affichées par le moteur d’activité dans le temps et ce à partir de plusieurs répétitions de la séquence audio.

**Comment by led78** [comment]
Si j'essaie d'écrire une automation pendant que les 96 pistes roulent avec la lecture d'automation en même temps, ça finit par surcharger au bout de quelques secondes.

**Comment by Normandeau** [comment]
Bien qu'on peut supposer que peu d'utilisateurs possèdent un MacPro, il est clair que les performances sont ici au rendez-vous!!! Merci pour ces tests.
