### ISSUE TITLE
ByPass inopérant du module 2X8 dans DP

### ISSUE THREAD

**Issue by VinyMo** [GRIS-UdeM/SpatGRIS-legacy#170]
Le ByPass du plugin ne fonctionne pas dans DP 9.13, que l'on soit en mode de trajectoire automatique ou en lecture d'automations; qu'on active directement avec le click de la souris ou avec un insert (enable/disable) dans la piste. C'est vrai que le plugin soit dans une piste auxiliaire et passe par des bus ou qu'il soit dans une piste régulière.

L'activation/désactivation par le checkBox du plugin est cependant opérante dans Reaper.

**Comment by Normandeau** [comment]
Exact. Le Bypass est problématique dans DP pour nombre de plugins. Flux a été obligé d'ajouter un Bypass supplémentaire dans chacun des plugins parce que celui de DP n'envoyait pas la bonne information aux plugins.
Avec Olivier, on a convenu que nous ne corrigerons aucun bogues de SpatGRIS dans la version actuelle du plugiciel. Comme vous le savez, Nicolas avait commencé une nouvelle version, réécrite à partir de zéro, dont l'interface est identique à la version actuelle. Dès que le Server est stable et qu'on peut le publier, Olivier va s'attaquer à SpatGRIS afin de le compléter et de corriger les bogues, nombreux, de la version actuelle. Les utilisateurs n'y verront que du feu entre la version 1.01 (que je viens de mettre sur SourceForge), et la version 1.2 disons.

**Comment by VinyMo** [comment]
Le ByPass du plugin fonctionne en 8X8 dans Dp 9.13; lorsque je le mets à la suite d'une Proverb mono to 7.1 qui n'envoie que dans les canaux 1,2,5 et 6 afin de les redistribuer sur l'ensemble de la couronne, l'activité des 8 vumètres passe à 4 lors de l'activation du ByPass.

**Comment by Normandeau** [comment]
Seule la version 2X8 est problématique. Testé 4X4 et 8X8 sans problème. Il semble y avoir une situation problématique générale dans DP à propos des plugiciels 2X8, que ce soit les MAS, les GRMTools ou SpatGRIS. J'ai testé avec les GRMTools qui font du 2X8 et le bypass ne fonctionne pas non plus,. J'ai écrit à Emmanuel Favreau à cet effet. J'ai écrit également à MOTU (sans grand espoir...)

**Comment by VinyMo** [comment]
C'est en fait presque toutes les situations de stereo to...dont le byPass est inopérant; 2X2 fonctionne - 2X4, 2X6 et 2X8 ne fonctionnent pas.

**Comment by Normandeau** [comment]
Commentaire d'Emmanuel Favreau des GRMTools:
Bonjour Robert,
J’avais aussi remarqué. DP n’envoie pas la commande bypass si les entrées/sorties sont différentes.
On ne peut rien y faire….
Emmanuel Favreau
Ina GRM | www.inagrm.com

**Comment by Normandeau** [comment]
Réponse de MOTU: ils n'arrivent pas à reproduire la situation, mais ils n'ont pas essayé ni les GRM, ni SpatGRIS. Deux familles de plugins basées sur Juce...

**Comment by Normandeau** [comment]
Dernier message de MOTU:
Actually just heard back from our lead developer. Here's what they said:
"We don't support bypass with surround plug-ins, as the source channels must still be distributed to the destination channels."
