### ISSUE TITLE
Différences entre le VST et l'Audio Unit

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS-legacy#174]
Suite à l'observation de certaines différences entre la version VST et la version Audio Unit de SpatGRIS (voir issue #173 ), j'ai pensé créer une issue dans laquelle nous pourrions répertorier celles-ci, s'il y en a d'autres.

Déjà, on constate que le menu déroulant permettant de choisir le nombre d'entrées et de sorties du plugiciel est différent. N'avions nous pas décidé d'éliminer les modes X16 suite à un problème, il y a quelques temps? J'ai tenté de retrouver une issue à ce sujet, sans succès.

![test_spatgris_04 2](https://user-images.githubusercontent.com/13606544/30302481-5d6ee2d8-972f-11e7-932c-15490790d6cf.png)

![test_spatgris_04 3](https://user-images.githubusercontent.com/13606544/30302489-62441288-972f-11e7-99cc-8fa4beb2cff1.png)

**Comment by Normandeau** [comment]
C'est la version X12 que nous n'étions pas certain de garder car elle ne fonctionne pas sous DP, qui a pourtant un mode 10.2. La version X12 fonctionne sous Reaper.
Pour ce qui est des AU vs VST sous Reaper, merci de noter les différences. Dans le manuel, il est clairement spécifié d'utiliser la version VST dans Reaper et AU dans Logic et DP. Aucun VST multiphonique ne fonctionne dans DP. Et Logic ne lit pas les VST.
