### ISSUE TITLE
quoi faire quand les automations se contredisent?

### ISSUE THREAD

**Issue by vberthiaume** [GRIS-UdeM/SpatGRIS-legacy#18]
_From @vberthiaume on September 1, 2015 15:38_

Si je suis en mode circulaire (ou autre mode non-indépendant) et j'ai ces automations enregistrées:
- la source 1 qui fait un cercle
- en même temps la source 2 fait un pendule

Chaque séquenceur répond de façon différente. À l'interne c'est une situation difficile à gérer mais je pourrais essayer d'ignorer les automations pour les sources non-sélectionnées quand on est en mode non-indépendant. 

Est-ce que ça vaut la peine de tenter de définir un comportement pour cette situation? Si oui quel devrait-il être?

_Copied from original issue: GRIS-UdeM/Octogris#54_

**Comment by vberthiaume** [comment]
Dans reaper, enregistrer l'automation pour une source, et ensuite pour une autre produit un "flickering" où la source sélectionnée alterne entre les 2 automations.

**Comment by Normandeau** [comment]
Réponse: remplacer l'utilisateur!

**Comment by vberthiaume** [comment]
hahaha excellent :)

On Fri, Aug 26, 2016 at 7:28 AM, Robert Normandeau <notifications@github.com

**Comment by Xon77** [comment]
Pour moi, les lignes d'automation pour les sources non-sélectionnées doivent être ignorées quand on est en mode non-indépendant.
Sinon, un flickering agaçant apparait dans Reaper : il est automatique avec les modes de mouvement Symetric X & Symetric Y, car ils font apparaître obligatoirement les enveloppes d'automation de la position X et Y de la 2ème source.
Pour résoudre ce problème de flickering, je dois constamment supprimer les lignes d'automation des positions des sources autres que la source 1 ou sélectionné, lorsque je ne suis pas en mode indépendant.
Ce comportement empêche aussi le basculement d'un mode indépendant à un autre mode, sans flickering.

**Comment by vberthiaume** [comment]
je suis d'accord que ce comportement devrait être le comportement par défaut. Ça risque d'être un peu compliqué de gérer ça à l'interne, mais je peux essayer!

**Comment by vberthiaume** [comment]
j'ai implémenté un fix simple pour ignorer les automations des sources non-sélectionées en mode non-indépendant. Ça fonctionne bien sous DP. Sous reaper, il faut quand même porter attention au modes d'écriture d'automation, genre read vs touch vs write.
