### ISSUE TITLE
SpatGRIS crashe DP systématiquement lors des passages d'une séquence à l'autre en mode 2X8

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#180]
SpatGRIS 1.01 en mode PanSpan, DP 9.02, 9.13 et 9.5
Depuis quelques jours j'assiste à des crashs systématiques de DP lors de l'opération suivante. Dans DP, il est possible d'avoir plusieurs Séquences dans le même Project (gérées dans la fenêtre Chunck). C'est une des caractéristiques originales de DP. On peut ainsi avoir toutes les séquences expérimentales, de traitement, de spatialisation et de composition dans le même projet. Ils partagent la même banque de son et la même banque d'instruments. C'est très efficace et très économique en terme de mémoire et d'espace disque. 
Depuis quelque temps, je travaille sur un nouveau projet dont tous les sons sont en stéréo. Je les mets en octophonie avec SpatGRIS en mode 2X8. Toutes mes séquences sont actuellement construites de cette manière. J'ai par exemple 4 séquences de 8 pistes chacune qui sont en mode 2X8. Lorsque je passe de l'une à l'autre DP crash systématiquement. Soit directement au moment du passage, soit lorsque j'appuie sur Play dans la nouvelle séquence.
Je viens de passer deux journées complètes à tenter de résoudre cela.
J'ai essayé DP 9.02, 9.13 et 9.5: c'est pareil.
J'ai tout enlevé DP deux fois et tout réinstallé le tout.
J'ai enlevé tous les plugins installés depuis un mois. J'ai effacé et refait tous les bundles. J'ai jeté et refait toutes les préférences de DP trois fois. Avec toujours le même résultat.
Je suis portant capable de jouer une séquence de DP avec 64 SpatGRIS en mode 2X8 avec automation sans problème (ce qui est très impressionnant) — ce qui démontre que ce n'est pas un problème de CPU—, mais dès que je passe d'une séquence à l'autre, ça crash.
La difficulté ici est de comparer un tel comportement. Seul DP à ma connaissance permet cette fonction. Je sais qu'on peut avoir plusieurs séquences ouvertes en même temps dans Reaper et Logic, mais elles sont indépendantes, comme autant de fichiers texte dans Word par exemple. Ici, c'est plutôt comme si la déconnexion audio ne se faisait pas proprement lors du passage dune séquence à l'autre. Pourquoi maintenant? Est-ce que ça faisait cela avant? Je ne le sais pas.
Peut-on tester cela?
PS1 Le mode OSC Spatialization ne pose aucun problème. Je viens d'ailleurs de tout remplacer dans ce projet et de mettre Server en mode octophonique pour pouvoir continuer à travailler. Mais c'est inquiétant pour SpatGRIS en mode audio...
PS2 J'ai désactivé le mode automatique de Crash Reporter de DP qui lui permet de les envoyer directement à MOTU sans les sauvegarder sur le disque dur de l'utilisateur et j'ai fait crasher DP deux fois de suite. Si ça vous tente de lire cela. Je viens de les envoyer chez MOTU, mais sans grand espoir...

[Crash 2X8.zip](https://github.com/GRIS-UdeM/SpatGRIS/files/1407302/Crash.2X8.zip)

**Comment by led78** [comment]
Il faudrait donc tester avec des anciennes version de SpatGris, voir OctoGris, afin de savoir si cela pouvait se produire avant? Si je comprend bien, toutes tes séquences comportent le même nombre de piste avec le même plug-in SpatGris 2x8 en mode Pan Span, reliées aux mêmes sorties?

**Comment by Normandeau** [comment]
Merci David. J'ai remplacé les SpatGRIS avec des Octogris (j'aurais pu y penser avant...) et cela a généré... un autre code d'erreur, au lieu d'un crash. Un code d'erreur audio. Je ne connais pas les codes de MOTU, mais cela m'a fait cliquer sur une chose: et si c'était une séquence qui était défectueuse, seulement une, et pas tout le projet?
Et c'était cela. Une séquence parmi une dizaine dans un projet DP. Je n'aurais pas pensé à cela en premier lieu. J'avais bien reconstruit le projet à partir des séquences individuelles à l'aide de la fonction Load de DP (très utile), mais en important une à une les séquences, je devais importer aussi le bogue de la séquence défectueuse.
Octogris a eu le mérite de faire en sorte que DP affiche un message d'erreur et bloque tout l'audio, au lieu de crasher.

![capture d ecran 2017-10-23 a 13 01 30](https://user-images.githubusercontent.com/8959779/31903477-349cba1e-b7f6-11e7-8442-c5c8019b6554.jpg)
