### ISSUE TITLE
Paramètres indéterminés du Spat 

### ISSUE THREAD

**Issue by VinyMo** [GRIS-UdeM/SpatGRIS-legacy#181]
Certains items dans le menu déroulant en entrée de piste DP et Parameter List dans Reaper renvoient à des paramètres obscurs du Spat: Speaker 1 - Un et Speaker 2 - Un

**Comment by VinyMo** [comment]
On voit dans Reaper qu'il y a une suite d'items _Unnamed_ . _Un_ renverrait à des paramètres non encore identifiés?

**Comment by led78** [comment]
Cette issue est brièvement mentionnée dans l'issue #176 . C'est bien de le noter plus spécifiquement.
