### ISSUE TITLE
Mode Random des Trajectoires: en mono seulement

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#182]
Lorsqu'on écrit le mode Random sur une piste autre que mono en Movements Independent, on devrait obtenir une écriture pour chacune des sources séparément. On a bien un mouvement Random des deux sources en stéréo au moment de l'écriture.
Mais on n'a que la source 1 qui s'enregistre, ce qui fait qu'à la reproduction on n'a qu'une seule source qui est automatisée.
J'ai essayé de mettre les sources en mode groupé avec l'option Force separate automation, mais le résultat est le même.
À corriger.

**Comment by Xon77** [comment]
Je n'observe pas ce comportement dans Reaper. Les automations s'enregistrent pour toutes les pistes stéréo ou octo aussi bien en Random qu'en random target (avec différents types de contraintes : circulaires ou indépendantes).

**Comment by VinyMo** [comment]
C’est d’ailleurs le cas également pour le mode Random Target.

Dans un autre ordre d’idée, mais toujours en lien avec le mode Random, Random Target offre l’option continuous ou discontinuous, fort sympathique pour éviter les larges sauts abruptes que le simple mode Random fait parfois; pourquoi cette option n’est-elle pas valable pour Random aussi?

D’autre part, Force Separate Automation est une option sur laquelle on peut s'interroger lorsqu’on choisit les Movements Circular Fully Fixed, Circular Fixed Radius ou Fixed Angle, plus rien de ces paramètres ne semble tenir lorsqu’elle est cochée, on retourne à un mode Random simple alors à quoi bon?
