### ISSUE TITLE
Crash systématique de DP en passant de OSC à Audio

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#183]
Une des caractéristiques intéressantes de SpatGRIS est la possibilité qu'il nous offre de passer d'un mode à l'autre, soit de OSC à PanSpan par exemple. Or lorsque j'essaie de passer d'une séquence construite avec SpatGRIS en mode OSC spatialisation vers le mode PanSpan, j'obtiens systématiquement un crash de DP (ce type de crash a d’ailleurs été à l'origine de la dégradation de ma séquence la semaine dernière).
Ce serait bien de valider ou d'invalider cela avec les autres séquenceurs. Je me doute que ce problème origine des presets. Ils ont toujours été problématiques depuis SpatGRIS. Or ma séquence fonctionne essentiellement avec des presets OSC à l'origine. Est-ce que ceux-ci sont incompatibles avec le mode audio? Possible.
Si c'est le cas, il faudrait trouver un moyen de corriger cela. Car l'idée de passer d'un mode à l'autre est au cœur de la refonte du plugiciel. Sur le plan de l'automation, on enregistre les mêmes paramètres: Source 1X et 1Y. Et les caractéristiques des trajectoires et des Movements. Reste le mode: OSC ou PanSpan. Dans le premier il n'y a pas de hp alors que dans le second il y en a. Et donc il y a toute une série de valeurs qui sont mémorisées dans un preset de l'un et pas dans l'autre.
Est-ce que cela doit automatiquement générer des crash? À vérifier.
Dans DP, ce n'est pas trop dramatique en ce sens où les paramètres d'automation ne sont pas effacés lorsqu'on enlève un plugiciel. Alors ici, je peux très bien conserver toutes mes données d'automation (trois jours de travail), enlever SpatGRIS OSC et remettre SpatGRIS Audio. Les trajectoires seront lues correctement.
Mais à ma connaissance dans Logic et Reaper par exemple, si vous enlever SpatGRIS, toute l'automation disparaît aussi...

**Comment by Xon77** [comment]
En passant de OSC à audio, je n'observe pas de crash dans Reaper. Mais comme je n'utilise généralement pas de presets, cela doit être la raison pour laquelle je n'ai pas de crash... Je vais tester avec les presets... Et oui dans Reaper, toute l'automation disparaît quand on enlève le SpatGRIS (je ne connais pas un moyen pour la conserver), ce qui peut être agaçant.

**Comment by VinyMo** [comment]
J’ai fait une séquence en mode osc avec automations sur les positions x,y de la source 1 et 2 pour des trajectoires Random indépendantes, et sur les spans Azimuth et Elevation, je passe au mode pan span sans problème, j’enregistre des automations sur le span qui s’ajoutent aux autres, je vais d’un mode à l’autre et n’observe aucun crash. Je n’ai sélectionné aucun preset dans une première situation. Puis, j’ai ensuite créé des presets en mode osc, j’en avais par ailleurs déjà plusieurs en mode pan span que je pouvais appelé, lorsque que j’appelle les presets d’un mode où de l’autre, le plugin passe de l’osc au mode audio et je n’observe aucun crash dans Dp. Même chose si je passe d’un mode à l’autre en passant par le menu déroulant. Je suis sur la version 9.13 de Dp.
