### ISSUE TITLE
Créer un Master Link des spans

### ISSUE THREAD

**Issue by led78** [GRIS-UdeM/SpatGRIS-legacy#185]
Avoir la possibilité de modifier les spans d'azimut et d'élévation simultanément à partir d'un seul des deux "sliders" serait très pratique. Souvent, je dois repasser deux fois pour écrire une automation jouant sur le span d'azimut et d'élévation alors que le tout pourrait être fait d'un seul coup si je pouvait lier temporairement ces paramètres.

**Comment by Normandeau** [comment]
ControlGRIS 100b4
C'est fait.
