### ISSUE TITLE
Presets en mode aléatoire

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#190]
Voici comment se présentent les Presets maintenant dans SpatGRIS.
D'après MOTU, c'est High Sierra qui serait responsable de cela. L'ordre alphabétique ne serait plus supporté par OSX!?! J'attends une explication plus détaillée de leur part. Ils ont publié la version 9.52 pour corriger ce problème:
• Added sorting code to work around the fact that macOS High Sierra is no longer guaranteed to sort files and folders in alphabetical order.
Avez-vous noter ce genre de problème sous High Sierra?

![spatgris random presets](https://user-images.githubusercontent.com/8959779/40184385-22a2601a-59be-11e8-80fe-7200dddc8c5d.jpg)

**Comment by Normandeau** [comment]
Je ne peux pas le croire:
Trouvé ici:
https://arstechnica.com/civis/viewtopic.php?f=2&t=1404045&start=80 
I'm curious about these APFS issues. It would seem to indicate that applications aren't as isolated from the underlying file system via the OS as I would have thought they would be.
It's mostly because many system APIs don't behave the same way they used to. For ex: If you use the Cocoa API to get the contents of a directory, on an HFS+ volume you'll get an alphabetically sorted list of its contents. (The alphabetical sorting is a by-product of how HFS+ stores contents of a directory.) On an APFS volume, the list of contents is in an arbitrary order.
Something simple like this could cause an app to do something like load its plug-ins and frameworks in a different order, and that could totally break the app.
In the API documentation Apple never promised the results would be alphabetical, but for over a decade they have been, so a developer could easily make that assumption. Apple could have tried to make the API work they way it used to, but since the contents of directories aren't stored sorted in APFS, to "fix" the API, the system would have to sort the contents of a directory every time an app asked for it, and that could easily create a performance problem.
Now imagine similar subtle shifts in behavior over several hundred file related APIs. Even good developers who code defensively will occasionally write in a bad assumption, and because things worked consistently for so long, those bad assumptions have never appeared in QA testing or user reports... until now =)
This happens under Windows as well, NTFS as an implementation detail returns directory listings in alphabetical (ish) order but the underlying OS makes no guarantees it will do so, and will happily return random results if the file system driver decides to.

**Comment by led78** [comment]
Wow,

Je n’ai pas encore fais le saut vers High-Sierra, j’attends?

David

**Comment by Normandeau** [comment]
Aussi sur le site d'Apple:

This happens also in other areas in Logic, for example, Custom Icons.
The problem is that in previous file systems, the system itself returned any file list in sorted order, so the app, didn't have to the sorting when it receives the list. The new APFS file system in HighSierra doesn't do that anymore (as Cuauhemoc pointed out). That means the Logic team has to update their code to now do the sorting on the receiving side inside Logic.
This is a perfect example why you always have to wait a month or two before upgrading an app or system if you have mission critical issues like that (There are also other even more annoying issues with HighSierra and Symlinks).

**Comment by Normandeau** [comment]
Problème réglé par Apple apparemment.
