### ISSUE TITLE
Automation n'est plus reconnue ou confuse dans 1.02

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#193]
Version 1.02
DP
Les données d'automation de SpatGRIS enregistrées avec la version 1.01 ne sont pas lues avec la version 1.02. La raison tient probablement au fait que les données enregistrées, qui portaient des noms explicites comme X, Y, AS et ES, sont maintenant remplacées par des données génériques:

![capture d ecran 2018-08-02 a 09 02 44](https://user-images.githubusercontent.com/8959779/43585836-118c87ee-9634-11e8-8e99-5f86c9eca658.jpg)

Je viens de passer deux mois à mettre au point une spatialisation très précise dans deux de mes pièces et là plus rien ne marche! À corriger impérativement.

Ce qui m'amène à une suggestion. Comme on entre dans une période de test intense, il serait préférable que les versions tests, autant du Server que du SpatGRIS, portent des noms de type ServerGRIS Beta et SpatGRIS Beta. De telle sorte qu'on puisse avoir sur nos machines des versions de production et des versions de tests installées en parallèle. Là je suis obligé d'enlever les nouvelles versions, car j'ai du travail de production à faire.

Logic
Tout est beau:

![capture d ecran 2018-08-02 a 09 26 56](https://user-images.githubusercontent.com/8959779/43586942-f9271edc-9636-11e8-8ca1-8ec5c50eff1e.jpg)

Reaper
Il y a confusion ici et le Radius est déjà pris en compte (RAD, X, X, Y):

![capture d ecran 2018-08-02 a 09 42 19](https://user-images.githubusercontent.com/8959779/43587510-633d50ba-9638-11e8-915f-e8dcb7b9fd95.jpg)

Mais différemment dans la piste suivante (X, Y, RAD, X):

![capture d ecran 2018-08-02 a 09 38 41](https://user-images.githubusercontent.com/8959779/43587342-ff2f9182-9637-11e8-88bf-0dda5f1f4efb.jpg)

**Comment by Normandeau** [comment]
Ordre des paramètres tels qu'ils apparaissent dans les trois logiciels avec la version 1.01:
DP:
![capture d ecran 2018-08-02 a 09 56 38](https://user-images.githubusercontent.com/8959779/43588920-912b5320-963b-11e8-8007-531da482727b.jpg)
Logic:
![capture d ecran 2018-08-02 a 09 57 41](https://user-images.githubusercontent.com/8959779/43588941-9c248a26-963b-11e8-9dcc-fe7aeaab8c06.jpg)
Reaper:
![capture d ecran 2018-08-02 a 10 04 03](https://user-images.githubusercontent.com/8959779/43588955-a3af2760-963b-11e8-804b-cfd27f97ec50.jpg)

**Comment by Normandeau** [comment]
Ordre des paramètres tels qu'ils apparaissent dans les trois logiciels avec la version 1.02:
DP:
![capture d ecran 2018-08-02 a 10 10 34](https://user-images.githubusercontent.com/8959779/43589426-ab1f3fac-963c-11e8-8313-84012eb28919.jpg)

Logic:
![capture d ecran 2018-08-02 a 10 11 20](https://user-images.githubusercontent.com/8959779/43589441-b44181c6-963c-11e8-81e2-1e34501e988a.jpg)

Reaper:
![capture d ecran 2018-08-02 a 10 12 12](https://user-images.githubusercontent.com/8959779/43589459-bdcec3b6-963c-11e8-919d-ad8765bfd8db.jpg)

**Comment by Normandeau** [comment]
On remarque qu'entre la version 1.01 et la version 1.02 on passe de 5 paramètres (X, Y, S, AS et ES; ou AS, ES, S, X et Y) à 6 paramètres (0, 1, 2, 3, 4 et5; ou AS, ES, RAD, S X et Y; ou X, Y, S, AS, ES, RAD).
C'est quoi le paramètre S? Est-ce qu'on en a besoin?
Est-ce que la confusion ne vient pas de là: un paramètre supplémentaire dans la liste?

Je remarque aussi que la version 1.02 n'est pas identifié, ni dans le Finder, ni dans les DAW. Elle apparaît seulement sous le no 1.0 A9lors que la précédente était identifiée 1.01)

**Comment by led78** [comment]
Ce pourrait-il que ce soit le Span (horizontal + vertical) combiné? #185

**Comment by Normandeau** [comment]
1.02
Testé avec DP, Reaper et Logic
**DP**
Comme mentionné dans une autre issue, l'automation n'est plus écrite dans DP.

**Reaper**
Pour le Radius, la fonction Link ne se reflète pas dans l'écriture de l'automation: les deux sources sont écrites:
![capture d ecran 2018-08-07 a 09 44 06](https://user-images.githubusercontent.com/8959779/43747699-7b04a440-9a26-11e8-99e2-69b3b472ba46.jpg)

**Logic**
Tout fonctionne comme prévu:
![capture d ecran 2018-08-07 a 09 40 01](https://user-images.githubusercontent.com/8959779/43747664-4dad3e44-9a26-11e8-8bf9-64dfd0f56c48.jpg)
