### ISSUE TITLE
Reset end point

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#42]
Juste de drôles de valeurs lorsqu'on fait un Reset end point:
![reset end point](https://cloud.githubusercontent.com/assets/8959779/13748075/a3ebb360-e9d1-11e5-935c-5000b748f53a.jpg)
Pourquoi ces valeurs-là en particulier?

**Comment by vberthiaume** [comment]
Comme nous avions discuté, et je pense que c'est ce qui fait le plus de
sens, la valeur "par défaut" pour le pendule est le point avec le même
rayon et un azimuth opposé (donc +/- 180) à la position courante.

2016-03-14 10:44 GMT-04:00 Robert Normandeau notifications@github.com:

**Comment by Normandeau** [comment]
Ok, d’accord, je comprends.
Je vais corriger le manuel.

Une question (je te la pose avant d»’essayer d’y répondre moi-même pratiquement): est-ce que les automations de SpatGRIS sont rétro compatibles avec l’un ou l’autre des deux plugiciels précédents?
Ce n’est que du X-Y qui s’écrit non?

Sinon, 120 téléchargements d’Octogris 3 en deux semaines (plus 78 pour les manuels)
ZirkOSC3, 12 téléchargements seulement mais 60 pour le manuel!!!
ON va faire que des manuels maintenant!

> Le 2016-03-14 à 10:52, Vincent Berthiaume notifications@github.com a écrit :
> 
> Comme nous avions discuté, et je pense que c'est ce qui fait le plus de
> sens, la valeur "par défaut" pour le pendule est le point avec le même
> rayon et un azimuth opposé (donc +/- 180) à la position courante.
> 
> 2016-03-14 10:44 GMT-04:00 Robert Normandeau notifications@github.com:
> 
> > Juste de drôles de valeurs lorsqu'on fait un Reset end point:
> > [image: reset end point]
> > https://cloud.githubusercontent.com/assets/8959779/13748075/a3ebb360-e9d1-11e5-935c-5000b748f53a.jpg
> > Pourquoi ces valeurs-là en particulier?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/GRIS-UdeM/SpatGRIS/issues/42.
> > 
> > —
> > Reply to this email directly or view it on GitHub https://github.com/GRIS-UdeM/SpatGRIS/issues/42#issuecomment-196348543.

Bonne journée

•••••••••••••••••••••••••••••••••••••••
Robert Normandeau
Vice-doyen aux études en création et technologie
Professeur titulaire de composition électroacoustique
Faculté de musique, B-660, 343-6111 poste 3486
Université de Montréal
http://musnum.musique.umontreal.ca/

**Comment by vberthiaume** [comment]
Je pense bien que les automations soient compatibles, que ce soit pour
l'octogris ou le zirkosc. À condition, bien sur, de mapper les bons
paramêtres. À priori, les noms des paramètres devraient être les même que
pour l'octogris.

Excellent pour les téléchargements! Et vraiment étrange qu'on ait plus de
downloads pour le manuel du zirkosc...!

2016-03-14 11:02 GMT-04:00 Robert Normandeau notifications@github.com:
