### ISSUE TITLE
Compatibilité de l'automation avec Octogris et ZirkOSC?

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#43]
Vincent a écrit:
«Je pense bien que les automations soient compatibles, que ce soit pour l'octogris ou le zirkosc. À condition, bien sur, de mapper les bons paramètres. À priori, les noms des paramètres devraient être les même que pour l'octogris.»
DP
Vérification faite, ce n'est pas compatible. Les paramètres sont les bons... partiellement. Car le séquenceur fait référence aussi au nom du plugin. Donc le X de Octogris n'est pas le même X que dans SpatGRis. Las valeurs enregistrées de Octogris ne sont pas lues par Spatgris:
![octospat](https://cloud.githubusercontent.com/assets/8959779/13813130/3a32d3fa-eb56-11e5-96d2-eb2b217caf99.jpg)
Et même chose avec ZirkOSC, les valeurs enregistrées par ce dernier ne sont pas lues par Spatgris::
![zirkspat](https://cloud.githubusercontent.com/assets/8959779/13813139/44a83b68-eb56-11e5-9861-d793eb2fd921.jpg)

Y aurait-il moyen de «leurrer» le séquenceur en lui disant que lorsque SpatGris est en mode audio, c'est une automation octogris qu'il écrit et lit, Et lorsqu'il est en mode OSC, c'est une automation ZirkOSC qu'il écrit et lit?
Ce serait génial, car cela assurerait une compatibilité avec les projets déjà réalisés.

**Comment by vberthiaume** [comment]
Bonne idée, je regarde ça!

2016-03-16 9:11 GMT-04:00 Robert Normandeau notifications@github.com:

**Comment by Normandeau** [comment]
Je remarque une autre différence: Octogris et Spatgris écrivent [Source 1 - X] etc. mais ZirkOSC n'écrit que [1 X] etc. Donc les données enregistrées par ZirkOSC ne sont pas les mêmes que pour Spatgris. Difficulté supplémentaire?

**Comment by Normandeau** [comment]
Même comportement dans Logic.

**Comment by vberthiaume** [comment]
Ouais, ça va être pareil partout. Et les noms des paramètres ont peut
d'importance (e.g., [1 X] vs [ ZirkOSC - 1 X ]), ce qu'il faut vérifier
c'est si on peut les changer dynamiquement...!

On Wed, Mar 16, 2016 at 9:45 AM, Robert Normandeau <notifications@github.com

**Comment by vberthiaume** [comment]
Je viens de regarder et c'est impossible de changer le _nom du plugin_ dynamiquement. Donc, par exemple, pour ce paramètre: 

`SpatGris [Source 1 - X]`

je pourrais peut-être (un gros peut-être) le changer dynamiquement en mode Osc Spat pour 

`SpatGris [1 X]`

ce qui le rendrais un peu plus près de ZirkOSC, mais il est impossible d'alterner entre 
`Octogris3 [Source 1 - X]` et `ZirkOSC3 [1 X]`.
