### ISSUE TITLE
Retour à la position de départ après l'écriture d'une trajectoire

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#44]
Lorsqu'une trajectoire arrive à la fin de son parcours, les sources devraient revenir à leurs positions de départ. Ce n'est pas toujours le cas. Ici, enregistrement d'une trajectoire, où on voit qu'à la fin, seule la source 2, donc l'esclave, revient à sa position de épart, la source 1 s'arrêtant à mi-chemin. Puis lorsque l'automation est lue, à la fin, aucune des deux sources ne revient à la position sauf après un certain temps.
Voici le film:
https://www.dropbox.com/s/g46ps93kk3bp4l1/Position%20de%20d%C3%A9part.mov?dl=0

**Comment by Normandeau** [comment]
Après observation plus minutieuse, notamment dans Logic, il semble que ça soit  plutôt dû à la lenteur de l'écriture de l'automation. En effet, le retour à la position de départ se fait instantanément, or les séquenceurs ne sont pas assez rapides pour écrire correctement le point final, alors ils en écrivent un quelque part, à mi-chemin. Il faudrait peut-être ajouter un délai de retour du genre 20-30 ms pour revenir au point de départ?

**Comment by vberthiaume** [comment]
regarder possible problème de performance?
