### ISSUE TITLE
Clics audio lors du croisement au centre

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#47]
Lorsque deux sources (ou plus) se croisent au centre, cela génère un clic audio lors de la lecture de l'automation enregistrée. Par exemple lorsqu'on utilise pendulum. Apparemment, ces clics ne sont pas générés lors de l'écriture de l'automation, seulement à la lecture de celle-ci.
Cela fait un moment que je veux poster ce bug que je connais depuis un bout de temps. Ce problème est hérité de Octogris. En fait, dans DP, c'est très flagrant avec Octogris. Cela n'apparaît pas avec Spatgris.
Vérification faite dans Logic, dans SpatGRIS le passage au centre d'un pendule génère un clic audio lors de la lecture de l'automation.
Dans les deux cas, les clics audio au centre sont beaucoup plus évidents lorsqu'on bouge les sources manuellement et rapidement.
Même problème avec Reaper.

**Comment by vberthiaume** [comment]
voir GRIS-UdeM/Octogris#111

**Comment by vberthiaume** [comment]
définitivement un problème audio avec les pendules "one-way" :

**Comment by vberthiaume** [comment]
problème seulement avec pan volume et pan span, pas free volume

**Comment by vberthiaume** [comment]
seulement en écriture+lecture manuelle?

**Comment by Xon77** [comment]
MacOS 10.12.3
Reaper 5.32
SpatGRIS 0.113

Comme déjà observé, il y a un clic audio lors du croisement de 2 sources au centre, en mode circulaire par exemple, dans beaucoup de types de configurations notamment 2x4, 2X6 ou 2x8, 2x16...
Je n'ai testé que sur les sorties stéréos de mon ordinateur, mais un clic est clairement perceptible lors de la lecture. Augmenter le smoothing à 500 ne règle apparement pas le problème...

**Comment by Xon77** [comment]
Des clics peuvent apparaître non pas seulement lors du croisement de plusieurs sources au centre : une seule source traversant le centre peut générer des clics.

**Comment by led78** [comment]
Tel que discuté avec Christophe aujourd'hui, depuis la version 2.1 de SpatGris:

Testé dans Logic Pro X 10.3.1
Système iMac 24-inch, début 2009
OS X El Capitan 10.11.6
Processeur 3,06 GHz Intel Core Duo
Mémoire 4 Go 1067 MHz DDR3
SpatGris 0.21 (Mode Pan Span)
Testé chez moi avec deux haut-parleurs

- Je perçois des clics et ce dans toutes les modes d'entrée et sortie, lorsque je bouge la source manuellement. 
- J'ai mis le paramètre de lissage (smoothing) à 1 ms pour provoquer le problème.
- Le problème survient surtout lors de la lecture de l'automation, mais aussi sans, quoique plus rarement et moins intensément.

**Comment by Xon77** [comment]
En testant les différentes versions sur Reaper 5.40,
en 2x2, avec une automation manuelle et un mouvement circulaire, j'observe ceci par rapport aux clics, en me rapprochant du centre et en tournant autour de celui-ci, aussi bien en enregistrement qu'en lecture d'automation  :

- version 0.1.12 : mode PanVolume, pas de clics, en tout cas pas observable. Pan span à 0, des légers clics, qui disparaissent quand on ouvre juste très légèrement le pan span. Le PanVolume n'est donc pas équivalent au PanSpan en termes de clics...

- version 0.1.13 : Le PanVolume est supposé être remplacé par le Pan Span à 0, et donc des légers clics sont audibles avec un pan span à 0 (par audible par défaut puisque le pan span est légèrement ouvert par défaut).

- version 0.2 : idem que la version précédente (introduction de la nouvelle fonction de vitesse de lecture)

- version 0.2.1 : des clics plus forts, même en augmentant fortement le pan span (introduits apparemment avec la nouvelle d'accélération ou free drawing ?)

- version 0.2.2 : les clics ont l'air équivalent à la version 0.2.1, bien que l'accélération ait été retirée. Le free drawing serait donc apparemment la cause de clics plus forts, même avec un pan span important... Ce qui est étrange : Pourquoi l’ajout de cette fonction (Free Drawing) a une incidence notable sur les clics ?

- version 1.0 : Retour à la dernière version 0.2, qui générait des clics moins forts et audibles que la version 0.2.1.

Solutions :
1. Ouvrir juste très légèrement le Pan span permet de supprimer complètement les clics. Pourquoi donc ne pas avoir par défaut une infime ouverture du pan span (0.0001…?) pour éliminer les clics, en empêchant de mettre le pan span à 0 ? Ou bien laisser la décision à l’utilisateur (en l'indiquant simplement dans le manuel), qui pourra augmenter très légèrement le pan span s’il observe des clics.

2. La réintroduction du PanVolume (de 0.1.12) permettrait également de supprimer complètement les clics.
