### ISSUE TITLE
VST: En lecture d'automation lorsque l'interface n'est pas ouverte, on perd l'automation

### ISSUE THREAD

**Issue by vberthiaume** [GRIS-UdeM/SpatGRIS-legacy#49]

**Comment by vberthiaume** [comment]
potentiellement relié au warning à la ligne 595 de l'éditeur

**Comment by vberthiaume** [comment]
je n'observe pas ce problème dans l'hexa... est-ce que quelqu'un est capable de le reproduire et de faire une liste des étapes pour le reproduire?

**Comment by Normandeau** [comment]
Ce n'est pas avec SpatGRIS que le problème se pose, mais avec Octogris. Voir une issue sur ce dernier.

**Comment by vberthiaume** [comment]
OK, je crois avoir réussi à reproduire le problème. Il semble que ça affecte octogris et spatgris. Voici les étapes que j'ai faîtes:
- Nouveau projet reaper
- mettre un fichier sonore sur une piste, e.g., une loop de techno plus ou moins bonne
- ajouter un vst spatgris ou un octogris sur la piste
- changer input/output mode pour 2x8
- superposer les 2 sources sonores et choisir le mode de mouvement "circular". Superposer les sources est optionnel, mais permet de facilement observer si la source non-sélectionnée ne suit pas l'automation.
- armer l'automation en write et enregistrer une automation manuelle (les trajectoires ne fonctionnent pas pour l'instant). Évidemment, il est important de s'assurer d'enregistrer l'automation seulement pour une source--ie, la source sélectionnée.
- désarmer l'automation (mettre en mode read), 
- Dans cet ordre précis: fermer le plugin, sauvegarder le projet et le fermer. 
- réouvrir le projet et bien observer que l'interface n'a pas été ouverte
- faire jouer le projet et entendre un genre de spatialisation vraiment étrange
- ouvrir l'interface du plugin et constater que le input/output mode est maintenant à 8x16, avec les sources et HP dans des positions étranges: 
  ![image](https://cloud.githubusercontent.com/assets/3721265/14154562/12e89e16-f68b-11e5-9a5a-c8f577259ac3.png)
- re-sélectionner le mode 2x8 et observer que tout redevient normal.

**Comment by Normandeau** [comment]
Vérifié ce matin avec la version AU: ce problème n'apparaît pas dans DP, ni avec Octogris 3.01, ni avec SpatGRIS 0.1
Dans Logic même chose.

**Comment by Normandeau** [comment]
Revenu à Reaper 5.12, à la suite de l'aveu du problème d'enregistrement et son apparente solution dans la version beta 5.20.
Le problème décrit ici avec les trajectoires écrites est le même avec la version VST et la version AU:
- lorsqu'on enregistre une trajectoire
- qu'on ferme l'interface (de SpatGRIS ou d'Octogris)
- qu'on sauvegarde le projet
- qu'on le ferme
- qu'on le rouvre
- qu'on lit la piste sur laquelle l'automation est enregistrée sans ouvrir la fenêtre du plugin
- l'automation ne fonctionne plus
- lorsqu'on ouvre la fenêtre du plugin, on revient toujours au mode 8 X 16
- remettre le mode 2 X 8 par exemple, règle le problème.

**Comment by Normandeau** [comment]
VST
Essai avec Reaper beta 5.20. Les trajectoires s'écrivent à nouveau, mais la lecture de l'automation reste problématique car le plugin VST revient toujours en mode 8 X 16 après la procédure décrite plus haut. Cela est vrai autant pour Octogris que pour SpatGRIS.
AU
Même comportement avec Octogris AU. 
Par contre avec SpatGRIS AU au lieu de revenir à 8 X 16, il revient à 2 X 2, le mode par défaut dans lequel il s'ouvre.
VST3
Avec SpatGRIS VST3 au lieu de revenir à 8 X 16, il revient à 2 X 2, le mode par défaut dans lequel il s'ouvre.

**Comment by vberthiaume** [comment]
Je crois avoir réglé le problème, je vais tester ça dans l'hexa mercredi prochain.
