### ISSUE TITLE
avec les vst et vst3 sous reaper, les trajectoires n'enregistrent pas d'automation. AU OK.

### ISSUE THREAD

**Issue by vberthiaume** [GRIS-UdeM/SpatGRIS-legacy#53]

**Comment by vberthiaume** [comment]
Le problème semble venir de reaper, probablement dans une version récente, parce que Octogris et ZirkOSC présentent exactement le même problème.

**Comment by Normandeau** [comment]
Je confirme qu'aucun de nos plugiciels — Octogris, ZirkOSC et SpatGRIS — ne permettent l'enregistrement de l'automation des trajectoires en mode VST dans Reaper. Et cela ni avec les version 2, ni avec les versions 3! L'enregistrement des trajectoires manuelles ne fonctionnent bien qu'en mode Write, surtout lorsqu'une première tentative d'enregistrement a été faite au préalable dan la même piste.
Toutes les versions AU fonctionnent normalement.
C'est quand même assez paradoxal dans la mesure où on vient de publier les versions 3 en mentionnant qu'il est préférable d'utiliser les VST dans Reaper...
Chez Reaper ils ont dû changer quelque chose dans les préférences de VST. Possible de fouiller un peu là-dedans, gang?
Précision: Reaper 5.17

**Comment by Xon77** [comment]
Je n'observe pas ce problème que ce soit pour Octogris ou Spatgris en VST, après avoir tout rescanné. Sûrement parce que j'ai Reaper 5.01... On en reparle demain...

**Comment by Normandeau** [comment]
Aucun problème avec la version 5.12 du 26 janvier 2016.
Par contre, aucune trajectoire enregistrée avec la version 5.15 du 15 février 2016.
À vérifier dans les «new features» de cette version:
http://www.reaper.fm/download-old.php

**Comment by Xon77** [comment]
Dans le whatsnew.txt de Reaper est indiqué :

v5.15 - February 9 2016
- Automation: automatically use absolute mouse editing for stepped pitch, fx param enum and toggle envelopes
  - Automation: improve sample accurate automation, fix parameter modulation issues with sample accurate plug-ins
  - Automation: improved automation recording behavior for toggle/enum parameters
  - Automation: improved automation recording for bypass envelopes in latch/write modes
  - Automation: improved automation recording for mute envelopes in latch/write modes
  - Automation: support enum/toggle FX parameter envelopes
  - Automation: improve accuracy of VCA envelope combination

Peut-être est ce l'une des raisons du non enregistrement ?

**Comment by vberthiaume** [comment]
Bonne nouvelle, apparement d'autres gens ont eu le même problème avec d'autres plugins, et reaper a déjà réglé le problème dans une version béta. 

Voir le [thread sur le forum de reaper](http://forum.cockos.com/showthread.php?t=174539). 
J'ai téléchargé la version béta [5.20 à partir d'ici](http://www.landoleet.org/), et le problème est réglé.

Note semi-reliée: il pourrait être intéressant pour nous de regarder les plugins qui ont eu le même problème que nous, si seulement pour comparer nos automations automatiques avec les leurs. Ils mentionnent: MAutoVolume de MeldaProduction, hornet autogain pro et dpMeter. J'imagine que c'est des plugins qui font du "fader riding"?

**Comment by vberthiaume** [comment]
Ah et est-ce qu'on devrait écrire une note sur notre page sourceforge pour mentionner le problème aux utilisateurs?

**Comment by Normandeau** [comment]
Aucun changement avec la version 5.18 de Reaper: les VST n’enregistrent pas de trajectoires alors les AU le font. Testés: Octogris et Spatgris.

**Comment by vberthiaume** [comment]
réglé avec la version 5.20
