### ISSUE TITLE
Pendulum à 90˚ et 270˚: saut direct

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#57]
Trajectoire de Pendulum, point de départ Source 1 à 90˚ sur le pourtour du cercle extérieur (valeur: 2), point d'arrivée à l'opposé, soit 270˚, la trajectoire fait un saut direct d'une extrémité à l'autre du cercle au lieu d'un pendule.
Valeurs de départ:
![pendulum90](https://cloud.githubusercontent.com/assets/8959779/14209772/be629f3a-f7f3-11e5-9afb-307fef4cfdb7.jpg)
Trajectoire écrite:
![pendulum90 automation](https://cloud.githubusercontent.com/assets/8959779/14209782/c718add6-f7f3-11e5-8966-57142f40506a.jpg)
La même chose se produit avec la valeur opposée au départ, soit 270˚
Aussitôt qu'on varie même d'une valeur infime comme 0.01 le réglage de l'angle, le problème disparaît.
Même problème dans Octogris.

**Comment by vberthiaume** [comment]
Excellente prise Robert...! Un bon vieux bogue comme on les aime :)
