### ISSUE TITLE
DP: plugin prends beaucoup de CPU

### ISSUE THREAD

**Issue by vberthiaume** [GRIS-UdeM/SpatGRIS-legacy#60]

**Comment by Normandeau** [comment]
Tant que cela?
Je viens de faire un test rapide dans les trois séquenceurs. 16 pistes stéréo et 8 pistes octo avec chacune un SpatGRIS en mode passif (pas d'automations).
Résultats:
DP: 600Mb mémoire; 35% CPU
Logic: 700Mb mémoire; 35% CPU
Reaper: 300Mb mémoire; 45% CPU.
Pas encore dramatique...

**Comment by vberthiaume** [comment]
Voir fix pour Octogris: https://github.com/GRIS-UdeM/Octogris/issues/114
