### ISSUE TITLE
OSC 1-2 actif en double

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#71]
Fait un test avec le Zirkonium MKIII et SpatGRIS 011 d'où il appert que les sources 1 et 2 sont toujours actives à leur position par défaut. Ainsi lorsqu'on ouvre SpatGRIS, les sources 1 et 2 oscillent entre leur position par défaut et la position effective dans SpatGRIS"
Ce problème apparaît avec n'importe combinaison de:
- Zirkokinium MKII
- Zirkokinium MKIII
- ZirkOSC 3
- SpatGRIS 011
  Voici un petit film:

https://www.dropbox.com/s/hf83lix1maojj96/OSC%201-2%20Actif.mov?dl=0 

Je n'avais jamais remarqué ce problème à ce jour.
Ce qui est étrange c'est que c'est systématique... Très bizarre.

**Comment by Normandeau** [comment]
Pour des raisons obscures ce problème n'apparaît plus ce matin. Je l'ai testé dans Reaper et Logic sans être capable de le reproduire. Puis de retour dans DP, dans une nouvelle session, pas de problèmes. Cela était probablement dû à l'usage d'une session «usagée»...

**Comment by vberthiaume** [comment]
Effectivement j'avais déjà eu ce bogue. C'est comme si DP gardait parfois
une vielle copie des plugins en mémoire...
