### ISSUE TITLE
ajouter mode x12

### ISSUE THREAD

**Issue by vberthiaume** [GRIS-UdeM/SpatGRIS-legacy#72]

**Comment by vberthiaume** [comment]
présentement, ce mode ne fonctionne pas dans DP (plugin n'est pas identifié comme compatible 10.2), et je ne suis pas certain de savoir comment faire le routing dans reaper pour utiliser les sorties 9-12.

**Comment by vberthiaume** [comment]
maybe related to #75 since DP uses audiounits?

**Comment by vberthiaume** [comment]
Question pour @Xon77: supposons que je veux faire du 2x12 dans l'hexa avec reaper, comment je configure le master pour qu'on utilise les bonnes sorties de la carte (ie, sauter les prises de micros et écouteurs)? J'ai fait ça mais je pense que les sorties ADAT 1-4 sont toujours à on (ie, non spatialisées par spatgris):

![image](https://cloud.githubusercontent.com/assets/3721265/17971669/c97c2f16-6aa9-11e6-8372-f56d712c219b.png)

**Comment by Xon77** [comment]
Bonjour Vincent,
Le plus simple pour moi serait de modifier les configurations d'attribution des sorties de la carte son dans la matrice de la Fireface settings (puisque que c'est spécifique à cette carte), puis d'enregistrer cette config en preset dans la carte son (si tu en as besoin souvent). 
Christophe

```
Le Jeudi 25 août 2016 9h54, Vincent Berthiaume <notifications@github.com> a écrit :
```

 Question pour @Xon77: supposons que je veux faire du 2x12 dans l'hexa avec reaper, comment je configure le master pour qu'on utilise les bonnes sorties de la carte (ie, sauter les prises de micros et écouteurs)? J'ai fait ça mais je pense que les sorties ADAT 1-4 sont toujours à on (ie, non spatialisées par spatgris):—

**Comment by Normandeau** [comment]
Merci Christophe, très bonne idée. Vive RME.
Pour Vincent, une image vaut mille mots.
Ça va être un peu différent dans le studio. Ici c'est une photo de la UFX qui comportent deux paires d'écouteurs. La 800 du studio n'en a qu'une.
Donc les 8 premières sorties ont associées aux 8 sorties analogiques.
Puis les 4 sorties suivantes, sont associées aux 4 premières sorties ADAT. Pour la 800, tu passes les Phones et la SPDIF:

![capture d ecran 2016-08-25 a 11 39 32](https://cloud.githubusercontent.com/assets/8959779/17975773/009e5442-6ab9-11e6-89a7-b997fb23b609.jpg)

Et tu sauvegardes le tout en deux clics:
- Bouton Store
- clic sur un des spapshots, que tu peux ensuite rebaptiser (comme ici: 12 Ch):

![capture d ecran 2016-08-25 a 11 44 37](https://cloud.githubusercontent.com/assets/8959779/17975917/582a257e-6ab9-11e6-85e3-43744a16755f.jpg)

**Comment by Normandeau** [comment]
Sinon, chez moi, le mode X 12 fonctionne bien dans Reaper.
Mais pas du tout dans DP. Dans ce dernier seuls les modes correspondants aux sources sont reconnus. 
- Si la piste est mono, seul le mode 1X2 est offert
- si la piste est stéréo, seuls les modes 1X2  et 2X2 sont offerts
  On ne peut pas associer une piste Quad ou une piste Octo à une sorties X12.

**Comment by Normandeau** [comment]
Copié de # 153:
Les modes 1X12 et 2X12 fonctionnent sans problème dans DP.
Le mode 12X12 ne fonctionne pas dans DP, bien qu'il soit possible de l'ouvrir.
Voici à quoi il ressemble:

12x12 dp

Tout est figé. Le Span ne fonctionne pas. Les Sources et les Speakers n'apparaissent pas. Et il n'y a pas d'audio.
Très rapidement la session finit par planter DP et alors il n'y a plus rien à faire, il faut effacer la piste sur laquelle on a mis un SpatGRIS 12X12. Même en testant différents Buffer Size et en revenant à 2048 (ce qui est très inhabituel dans des modes de fonctionnement normaux. J'utilise toujours 1024, voir 512 en situation de concert).
Dans DP, on ne peut pas faire de mixage complexe: par exemple on ne peut pas faire de combinaisons comme 4X6, ou 4X8 ou 4X12. Ainsi ici, on ne peut pas faire de 4X12, de 6X12 ou de 8X12, ce qui serait parfois utile. C'est une limite de DP.

Reaper
Tous les modes X12 fonctionnent dans Reaper, sauf 12X12, qui se comporte exactement comme dans DP: tout est figé.

Quant au mode 16X16, il n'est tout simplement pas implémenté encore. Il sera incompatible avec tous les séquenceurs audio, sauf Reaper.

**Comment by Normandeau** [comment]
Copié de # 153:
https://forum.juce.com/t/resolved-issue-for-more-than-8-channels/19993/12

**Comment by Normandeau** [comment]
Plus nécessaire de se préoccuper de cela. Au-delà des limites du séquenceur, le Server prend le relai de SpatGRIS.
