### ISSUE TITLE
Avec un nouveau projet Reaper, seulement les outputs 1 et 2 ont du son

### ISSUE THREAD

**Issue by vberthiaume** [GRIS-UdeM/SpatGRIS-legacy#74]
Même problème dans Octogris, pas de problème avec DP ou Logic. Testé versions 5.20 et 5.22.

**Comment by vberthiaume** [comment]
semble être un problème de reaper, DP et Logic OK.

**Comment by vberthiaume** [comment]
problème est toujours là avec version 5.2.2...

**Comment by vberthiaume** [comment]
même problème sous windows

**Comment by Xon77** [comment]
En effet, bien que les vumètres affichent du signal rien ne sort vers les sorties autres que 1 et 2. Apparemment, les canaux impairs vont vers la sortie 1 et réciproquement. 

 Le Mardi 23 août 2016 12h18, Vincent Berthiaume notifications@github.com a écrit :

 même problème sous windows—

**Comment by vberthiaume** [comment]
par contre je n'ai pas ce problème si j'ouvre un vieux projet, par exemple celui ci: 

https://www.dropbox.com/s/nclcsump7biwqkf/OctogrisAndSpatgrisClickReaper.zip?dl=0

Je pense que c'est donc soit un problème dans la création de nouveaux projets reaper, ou bien il y a une nouvelle façon de configurer les entrées/sorties des pistes que je ne comprends pas. Est-ce que quelqu'un peut investiguer:
1. Quelle version de Reaper produit des projets qui spatialisent correctement?
2. Est-ce qu'il y a des paramêtres qu'il faut ajuster dans le routage ou autre pour faire fonctionner la spatialisation correctement avec les nouveaux projets?

**Comment by Normandeau** [comment]
Testé Reaper 5.22 et 5.23 (la dernière) aucun problème particulier avec Spatgris 2X8 ou 8X8.
Configuration de piste:

![capture d ecran 2016-08-23 a 13 15 26](https://cloud.githubusercontent.com/assets/8959779/17902264/a0914bca-6934-11e6-9976-89cc8bd2e6d1.jpg)

Configuration du Master:

![capture d ecran 2016-08-23 a 13 15 13](https://cloud.githubusercontent.com/assets/8959779/17902279/ab5bec7c-6934-11e6-8e89-9aad5acb0008.jpg)

**Comment by vberthiaume** [comment]
Avec mon projet ou un nouveau projet? C'est normal que tu n'aies pas de
problèmes avec mon projet parce qu'il vient d'une vielle version.

On Tue, Aug 23, 2016 at 1:23 PM, Robert Normandeau <notifications@github.com

**Comment by Xon77** [comment]
En essayant la plus ancienne version que j'ai 5.01 -> 5.23, je n'ai pas de son pour les sorties > 2.J'essaie différentes configs de routing, mais pour l'instant rien ne change...  

```
Le Mardi 23 août 2016 12h57, Vincent Berthiaume <notifications@github.com> a écrit :
```

 par contre je n'ai pas ce problème si j'ouvre un vieux projet, par exemple celui ci: https://www.dropbox.com/s/nclcsump7biwqkf/OctogrisAndSpatgrisClickReaper.zip?dl=0Je pense que c'est donc soit un problème dans la création de nouveaux projets reaper, ou bien il y a une nouvelle façon de configurer les entrées/sorties des pistes que je ne comprends pas. Est-ce que quelqu'un peut investiguer:   
- Quelle version de Reaper produit des projets qui spatialisent correctement?
- Est-ce qu'il y a des paramêtres qu'il faut ajuster dans le routage ou autre pour faire fonctionner la spatialisation correctement avec les nouveaux projets?

**Comment by Normandeau** [comment]
Nouveau projet pour la version 5.22 et la version 5.23
Aucun problème à Orford avec la 5.22 ni avec Spatgris, Octogris ou Zirkosc!!!

Envoyé de mon phoni

**Comment by Xon77** [comment]
En modifiant les options de routing de manière des pistes et du master de manière appropriée par rapport au nombre de sorties, par exemple :
J'arrive à voir du signal dans toutes les sorties avec un nouveau projet (Reaper 5.23 & Spatgris 1.4). Je ne peux pas contrôler le rendu exact de la spatialisation pour l'instant, car je n'ai pas d'enceintes chez moi, mais cela me paraît correct. 

```
Le Mardi 23 août 2016 13h57, Robert Normandeau <notifications@github.com> a écrit :
```

 Nouveau projet pour la version 5.22 et la version 5.23
Aucun problème à Orford avec la 5.22 ni avec Spatgris, Octogris ou Zirkosc!!!

Envoyé de mon phoni

**Comment by vberthiaume** [comment]
Christophe, est-ce que tu as oublié quelque chose après cette phrase:

En modifiant les options de routing de manière des pistes et du master de

> manière appropriée par rapport au nombre de sorties, par exemple :

Je pense que j'ai peut-être justement besoin d'un exemple sur comment
modifier les paramètres de routing! :)

2016-08-23 14:18 GMT-04:00 Christophe Lengelé notifications@github.com:

**Comment by Xon77** [comment]
Je t'envoie ci-joint la capture d'écran du routing du master. Je pensais que l'image était passée. A faire aussi pour le routing des pistes et du master.Les tracks channels en haut doivent être configurés en fonction du nb de sorties. Et en bas, il faut sélectionner 1-8 Multichannel source dans le routing du master. 

```
Le Mardi 23 août 2016 14h40, Vincent Berthiaume <notifications@github.com> a écrit :
```

 Christophe, est-ce que tu as oublié quelque chose après cette phrase:

En modifiant les options de routing de manière des pistes et du master de

> manière appropriée par rapport au nombre de sorties, par exemple :

Je pense que j'ai peut-être justement besoin d'un exemple sur comment
modifier les paramètres de routing! :)

2016-08-23 14:18 GMT-04:00 Christophe Lengelé notifications@github.com:

**Comment by vberthiaume** [comment]
AH! Mon problème était effectivement que je n'avais pas configuré le routing dans la master track. 

Routing pour piste octo:
![image](https://cloud.githubusercontent.com/assets/3721265/17906103/dd8f9626-6943-11e6-82ff-6389b1ce9b97.png)
Routing pour master track:
![image](https://cloud.githubusercontent.com/assets/3721265/17906123/e895fd94-6943-11e6-9452-dd69f2c29cf0.png)
Merci!
