### ISSUE TITLE
to upgrade to juce 4.2.0 and above, need xcode 7.3.1 and el capitan

### ISSUE THREAD

**Issue by vberthiaume** [GRIS-UdeM/SpatGRIS-legacy#75]
this is apparently only compatible with xcode 7.3.1. and hexa has 7.2.1.

https://developer.apple.com/library/ios/samplecode/AudioUnitV3Example/Introduction/Intro.html

updating to juce 4.2.0 and above seems to causes problems with speakers being inverted, see #73.

**Comment by vberthiaume** [comment]
we need el capitan to use xcode 7.3.1, so wait for now

**Comment by Normandeau** [comment]
Est-ce une priorité? Je viens de poser la question à Jean-Michel pour connaître les plans de la fac à cet égard. La seule conséquence prévisible dans Hexa est que nous allons perdre l'usage d'Audiosculpt de l'IRCAM, qui nécessite une mise à jour pour El Capitan (les enfoirés). Pas grave, on peut racheter une licence (les enfoirés, bis).

**Comment by vberthiaume** [comment]
Non, je ne pense pas que ce soit une priorité. Il y a une faible probabilité que ça règle le problème avec les 12 sorties sous DP (#72), mais je peux tester ça ailleurs. C'était plus une note à moi même pour me rappeler de regarder ça, une fois qu'on sera tous sur el capitan.

**Comment by Normandeau** [comment]
Voici la réponse de Jean-Michel:
«J’ai expérimenté pas mal El Capitan cet été puisque le nouvel ordi du multipiste ne peut pas être sur une version plus basse et je ne recommande pas de faire la migration nulle part ailleurs pour le moment.
La plupart des applications audio sont fonctionnelles mais il y a un gros bug avec les claviers et les souris qui rend le travail très frustrant. Apple est au courant depuis la sortie de El Capitan.
J’en reviens pas qu’en 2016 on doive se battre avec des périphériques aussi simple qu’une souris!
De plus, la plupart des nouvelles fonctionnalités sont problématiques pour le travail de studio (synchronization automatique, notifications incessantes, power nap, etc…).»
Donc si nécessaire, ce qu'on peut faire cependant, c'est de créer une nouvelle partition sur le disque dur du studio avec El Capitan comme OSX.
À toi de décider.
Personnellement, je passe mon tour...

**Comment by vberthiaume** [comment]
Aucun problème, et aucunement besoin d'une nouvelle partition!

2016-08-26 10:40 GMT-04:00 Robert Normandeau notifications@github.com:
