### ISSUE TITLE
La trace laissée par le joystick est jaggy

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#76]
La trace laissée par l'utilisation du joystick dans SpatGRIS 0.13 est jaggy. C'est la même chose dans Octogris 304 et 305 .

![octogris304 et joystick](https://cloud.githubusercontent.com/assets/8959779/17387452/056489c2-59c2-11e6-93a5-b0b83fb5d169.jpg)

**Comment by vberthiaume** [comment]
avec 5b0b2e0, la trace pour le joystick va maintenant être beaucoup moins longue, quoi que toujours jaggy.

**Comment by vberthiaume** [comment]
La raison pour laquelle la courbe est "jaggy" est qu'avec la librarie qu'on utilise, on reçoit la position du joystick toujours en 2 parties: on a d'abord une nouvelle position x, et ensuite une nouvelle position y. Ça peut aussi être dans l'ordre inverse, ou seulement une nouvelle valeur x ou seulement y si l'utilisateur n'a déplacé le joystick que directement dans la direction d'un axe. Il est possible qu'en changeant complètement la librairie (ce qu'on devra faire de toute façon pour permettre l'utilisation du joystick sous windows. #58), ce problème soit réglé, mais sinon, la trace (et la position) du joystick est effectivement jaggy. Je doute que ça soit audible...
