### ISSUE TITLE
Pas de VU-mètres dans DP

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#79]
Situation: plusieurs pistes stéréo, plusieurs sorties octo.
Ce problème ne se pose qu'avec la version 2X8 d'Octogris et de Spatgris. Les versions 2X2 et 8X8 ne posent pas ce problème.
Lorsqu'on utilise Spatgris 0.13 ou Octogris 3.05 dans DP9.1, les Vu-mètres de pistes de celui-ci ne fonctionne plus et indique de façon aléatoire une activité permanente.
Voici à quoi ça ressemble. On remarquera que j'ai mis un Trim avec un une valeur de mesure à -120dB. Il n'y a pas d’activité audio sur les pistes, cela ne semble générer de bruit de fond et cela ne semble pas nuire à l’audio. Mais c'est très étrange!
Remarque: je constate cela avec DP 9.1 qui est sorti cette semaine. Je vais vérifier avec DP 9.02 installée sur l'ordi du dôme pour voir si j'ai le même comportement. La version de Logic est 10.24, soit la plus récente..

![spatgris pas de vu-metre dans dp](https://cloud.githubusercontent.com/assets/8959779/17457845/3fa3f620-5bd1-11e6-899c-5ccf423fc1da.jpg)

Dans Logic, le problème est différent entre Octogris et Spatgris. Avec Octogris, tout va bien. Avec Spatgris, lorsque qu'on fait rouler la session, les vu-mètres s'activent et lorsqu'on l'arrête, les vu-mètres restent figés là où ils étaient au moment de l'arrête. Dès qu'on repart la session, les vu-mètres sont resettés.
Voici à quoi ça ressemble (la session est à stop ici):

![spatgris drole de vu-metre dans logic](https://cloud.githubusercontent.com/assets/8959779/17457870/b97affde-5bd1-11e6-9333-20d95a0de736.jpg)

**Comment by Normandeau** [comment]
Vérification faite, le problème ne se pose pas dans les versions précédentes des deux logiciels. Ni dans la version précédente de Logic, ni dans celle de DP. Humm, beau problème en perspective... N'empêche que ce n'est que la version 2X8 qui pose problème. Il me semble que ça me rappelle quelque chose.
Et il y a tellement de bogues rapportés déjà que je suis revenu en arrière. Première foi que je dois faire cela avec DP!
On attend une mise à jour de DP. Je vais leur écrire... si je trouve à qui!!! Mais apparemment ils attendent du feedback car ils ont changé pas mal de choses dans la gestion des buffer size des plugiciels.

**Comment by vberthiaume** [comment]
Donc si je comprends bien, on pense que c'est un bogue des séquenceurs?

**Comment by Normandeau** [comment]
Oui et non. Je viens de relire attentivement le Read Me au sujet de la version 9.1 Un des premiers changements qu'ils ont faits est le suivant:
• Track level meters now display the track's level post-fader and pre-pan. 
Ce qui veut dire que si tu modifies le pan d'une piste, les VU-mètres ne reflète pas ce changement!. Drôle d'idée.
Cependant, lorsqu'on insère SpatGRIS dans une piste, les VU-mètres de DP se comportent comme avant, c'est-à-dire post-fader et post-pan. Une piste de solution?
J'aimerais aussi ajouter que lorsqu'il y a de l'audio qui joue sur une piste en mode 2 X 8, seuls les VU-mètres 1 et 2 (ou L et R) de la piste affiche de l'activité. Les VU-mètre 3 à 8 ne fonctionnent pas:

![vu meters 1-2 in dp 9 1](https://cloud.githubusercontent.com/assets/8959779/17938159/cd0cbaf4-69f2-11e6-8fc0-2dac5929717d.jpg)

Cela étant dit, le VU-mètre de la piste Master Track fonctionne très bien. Et tout cela n'affecte pas l'audio, qui est tout à fait normal.
Je viens d'écrire un rapport détaillé à MOTU, mais comme le problème ne se produit qu'avec une seule instance de notre plugiciel, la 2 X 8, je crains que ça rebondisse dans notre cour.

**Comment by Normandeau** [comment]
Ils testent de leur côté Je leur ai envoyé le lien vers Octogris et SpatGRIS. Et une vidéo.

**Comment by Normandeau** [comment]
Vincent a écrit:
En lisant ce que tu m'a envoyé, on dirait qu'une possible cause du problème serait que DP assume qu'on a le même nombre de sorties que d'entrées. Donc le mode 2x2 fonctionne bien, parce qu'on a le même nombre d'entrées et de sorties, mais dans le mode 2x8, DP va quand même lire "en mémoire" dans les entrées 3,4,5,6,7 et 8, et affiche ce qu'il trouve (qui est n'importe quoi qui se trouve dans le ram à cette adresse) sur les VU-mètres. Avec cette hypothèse, il serait possible qu'on ait des problèmes similaires pour tous les modes où on a plus de sorties que d'entrées (1x2, 2x6, 4x8, etc).

**Comment by Normandeau** [comment]
Tests exhaustifs dans DP9.1 (je ne peux pas vérifier l'audio, car je n'ai pas de carte-son en fin de semaine. Je me fie à ce que je vois...):
**Fichier mono**
- 1 vers 2: Ok
- 1 vers 4: sur la piste mono, seuls les VU mètres 1-2 du mixeur de DP fonctionnent. Les 3-4 ne fonctionnent pas. Par contre sur le panner, ils fonctionnent tous. Sur la sortie Master Quad, ils fonctionnent tous.
- 1 vers 6: sur la piste mono, seuls les VU mètres 1-2 de DP fonctionnent. Les 3-4 et 5-6 ne fonctionnent pas. Par contre sur le panner, ils fonctionnent tous. Sur la sortie Master 5.1, ils fonctionnent tous.
- 1 vers 8: sur la piste mono, seuls les VU mètres 1-2 de DP fonctionnent. Les 3-4, 5-6 et 7-8 ne fonctionnent pas. Par contre sur le panner, ils fonctionnent tous. Sur la sortie Master 7.1, ils fonctionnent tous. Et on a une activité statique sur certains VU-mètres de la piste (ici, le 7, mais ça semble aléatoire):

![capture d ecran 2016-09-02 a 11 46 51](https://cloud.githubusercontent.com/assets/8959779/18209796/5bcbe3d4-7103-11e6-8f5a-595f5c21ae1e.jpg)
- 1 vers 12: ne fonctionne pas

**Fichier stéréo**
- 2 vers 2: Ok
- 2 vers 4: sur la piste stéréo, seuls les VU mètres 1-2 du mixeur de DP fonctionnent. Les 3-4 ne fonctionnent pas. Par contre sur le panner, ils fonctionnent tous. Sur la sortie Master Quad, ils fonctionnent tous.
- 2 vers 6: sur la piste stéréo, seuls les VU mètres 1-2 de DP fonctionnent. Les 3-4 et 5-6 ne fonctionnent pas. Par contre sur le panner, ils fonctionnent tous. Sur la sortie Master 5.1, ils fonctionnent tous.
- 2 vers 8: - 1 vers 8: sur la piste stéréo, seuls les VU mètres 1-2 de DP fonctionnent. Les 3-4, 5-6 et 7-8 ne fonctionnent pas. Par contre sur le panner, ils fonctionnent tous. Sur la sortie Master 7.1, ils fonctionnent tous. Et on a une activité statique sur certains VU-mètres de la piste (qui semble aléatoire)
- 2 vers 12 : ne fonctionne pas

Rappel, voici un panner QUAD dans DP (on voit qu'il y a du signal sur le VU-mètre 4):
![capture d ecran 2016-09-02 a 11 43 10](https://cloud.githubusercontent.com/assets/8959779/18209628/9714a206-7102-11e6-919a-6291bbea6caf.jpg)

**Comment by vberthiaume** [comment]
Wow, super tests Robert!

Quand tu dis "ne fonctionne pas", e.g, "2 vers 12 : ne fonctionne pas",
est-ce que tu veux simplement dire que les VU-mètre n'affichent aucune
activité, ou genre que le plugin n'est pas disponible du tout?

2016-09-02 12:00 GMT-04:00 Robert Normandeau notifications@github.com:

**Comment by Normandeau** [comment]
Le plugin n'est pas disponible du tout. Lorsqu'on veut placer SpatGRIS sur une piste 1X12 ou 2X12, le seul choix qu'on a dans la liste des plugiciels disponibles est la version mono à stéréo (piste mono) ou stéréo (piste stéréo).
- 4 vers 4: Ok
- 6 vers 6: Ok

Par ailleurs, un fichier QUAD, ou 5.1 ne peut être ouvert que dans une sortie QUAD ou 5.1. On ne peut pas placer un fichier QUAD sur une sortie 7.1 par exemple. Ou un fichier 6.1 sur une sortie 10.2.

**Comment by Normandeau** [comment]
De MOTU, 16-10-21. Rare qu'une compagnie admette que la balle est dans son camp:
Thank you for following up, and I apologize for the delay of this message. It appears that this issue has more to do with DP's surround implementation than with your plug-in. This is an issue that has been submitted to the Development Team, who are working to address it as quickly as possible. I apologize again for the late response here, and I will be sure to notify you via this MTL when any new information is available. Please let me know if you need anything else in the meantime.

**Comment by Normandeau** [comment]
Dernière nouvelle de MOTU:
«Thank you for following up, and I apologize for the delay of this message. It appears that this issue has more to do with DP's surround implementation than with your plug-in. This is an issue that has been submitted to the Development Team, who are working to address it as quickly as possible. I apologize again for the late response here, and I will be sure to notify you via this MTL when any new information is available. Please let me know if you need anything else in the meantime.»

**Comment by Normandeau** [comment]
Juste une info complémentaire ici. Je viens de faire des tests supplémentaires avec des plugiciels autres que les nôtres: GRMTools SpaceGrain et Delay, eVerb et ProVerb (ces trois derniers de MOTU), tous capable d'un mode 2X8 (nommé stereo to 7.1). Et bien c'est le même phénomène avec tous ces plugiciels: les VUMètres 1 et 2 fonctionnent, mais pas les autres. Et on a divers signaux qui s'affichent au maximum en permanence de manière statique.
Ici, avec SpaceGrain:

![2x8 metering problem](https://cloud.githubusercontent.com/assets/8959779/23333541/26f5078e-fb5b-11e6-9f9b-706abb2c5706.jpg)

**Comment by led78** [comment]
J'ai testé la chose (seulement avec 2 haut-parleurs cependant) chez moi et le problème semble résolu dans Logic Pro X, depuis la version 10.3.1.

Système: OS X El Capitan 10.11.6
iMac (24-inch, early 2009)
Processeur: 3,06 Ghz Intel Core 2 Duo
Mémoire 4 Gb 1067 MHz DDR3

J'ai testé les modes suivants disponibles : 1x1, 1x2, 1x4, 1x6, 2x2, 2x4 et 2x6
- Tous les VU-métres fonctionnent normalement dans Logic dans tous les cas. Aucun gèle.
- Le son sortant de mes deux haut-parleurs est cohérent avec ce que je vois à l'écran. Je n'entend aucun clics.
- Toutefois, dans tous les cas, ce sont plutôt les VU-mètres dans SpatGris qui gèlent, dès que je démarre une trajectoire, peu importe laquelle.

**Comment by led78** [comment]
Testé chez moi avec deux haut-parleurs
Logic Pro X 10.3.1
Système iMac 24-inch, début 2009
OS X El Capitan 10.11.6
Processeur 3,06 GHz Intel Core Duo
Mémoire 4 Go 1067 MHz DDR3
SpatGris 0.21

Après plusieurs tests avec le mode 2X8 sur une piste Surround 7.1 (SDDS) je n'observe plus ce problème de VU-mètre figé dans Logic. La version 10.3.1 de Logic semble avoir réglé la chose.

J'ai donc retiré Logic du titre.
