### ISSUE TITLE
Automation des Movements

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#80]
Cela pourrait être utile de pouvoir automatiser des changements du paramètre Movements.

**Comment by Normandeau** [comment]
Mode OSC
Je vois que l'automation des Movements est prévue dans SpatGRIS 0.17, mais dans DP9 elle n'est pas lue.
Ni dans Reaper.
Mode Audio
Il semble qu ça ne marche pas non plus en mode audio (testé très rapidement).
Pourriez-vous tester cela rapidement? Logic, DP, Reaper.

**Comment by Normandeau** [comment]
Une question: comment l'automation de ce paramètre fonctionne-t-il? Je note que c'est un paramètre continu (0 à 1) alors que le nombre de Movements est limité à 8. Cela soulève la question des paramètres discrets ou scalaires. Dans les GRMTools par exemple, les paramètres scalaires apparaissent avec leur nom:

![grmtools echelle scalaire](https://cloud.githubusercontent.com/assets/8959779/20033565/9aa4f110-a379-11e6-9fc2-a3b3182c6e9e.jpg)

Peut-on imaginer quelque chose du genre?

**Comment by vberthiaume** [comment]
Effectivement, l'automation pour le mode de mouvement est écrite mais ne fait rien! Je m'en occupe. Pour ce qui est des paramètres des plugins, ils sont toujours encodés en continu de 0 à 1, le standard est juste fait comme ça. Je pense que ce que les GRM tools font est peut-être simplement changer le nom du paramètre? Je regarde ça.

**Comment by Normandeau** [comment]
J'ai aussi vérifié avec des plugins de MOTU. Par exemple dans MWEQ, pour les filtres passe-haut et passe-bas, il n'y a que 6 réglages: de -6dB/octave à -36dB/octave.
Quand on automatise ces paramètres, ils sont indiqués comme tels dans la fenêtres des événements du séquenceur, et non pas en valeurs continues.

**Comment by vberthiaume** [comment]
ok, je vois maintenant que l'automation ne s'écrit juste pas dans DP, alors qu'elle s'écrit (et se lit, quoi que mal) dans reaper

**Comment by Normandeau** [comment]
Je n'arrive pas à faire lire l'automation des Movements dans Reaper. J'ai essayé chez moi et dans Hexa. Effectivement l'automation s'écrit, mais SpatGRIS ne la lit pas par la suite. J'ai essayé en mode Pan Volume et en mode OSC Spatialization.

**Comment by Xon77** [comment]
Bien que l'écriture de l'automation des mouvements apparaisse, je confirme les observations de Robert concernant la non-lecture des automations de mouvement, dans Reaper : l'automation de mouvement prend apparemment la dernière sélectionnée.
