### ISSUE TITLE
L'automation OSC ne fonctionne pas en arrière-plan et coupe l'audio

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#83]
SpatGRIS en mode OSC ans Reaper. Testé avec Soundflower. 64 canaux total. Sessions de ± 16-40 canaux, pistes stéréo.
Tous mes étudiants ont eu le même problème ici. Dans Reaper, avec de l'automation écrite ou pas dans les pistes, la position des sources n'est pas active dans le Zirkonium MKII si la fenêtre du SpatGRIS n'est pas ouverte. Et non seulement l'automation ne suit pas, mais en plus, à partir d'un moment, cela coupe complètement l'audio, de toutes les pistes! La seule façon de le retrouver est d'ouvrir toutes les fenêtres de SpatGRIS. C'est très ennuyant dans une session de 40 pistes!
Comparaison rapide, mais avec une seule piste ce matin: ZirkOSC ne semble pas avoir le même comportement. Dans ma mémoire c'était un bogue réglé depuis cet hiver, non?
Est-ce qu'on peut se mettre en beta testing rapido: 
- vérification dans Reaper, Logic et DP et pas seulement avec deux pistes mais avec un minimum de 32 canaux ouverts.
- est-ce que cela se produit tout le temps ou seulement à partir d'un certain nombre de pistes. Cela signifie qu'il faut tester avec une session dans laquelle on ouvre des pistes progressivement. Jusqu'à ce que rien ne fonctionne.
- est-ce que le même problème se pose en mode audio, c'est à dire Pan Volume et Pan Span par exemple. Même série de tests.
  Du pain sur la planche car ceci est un probléme majeur.

**Comment by vberthiaume** [comment]
Chez moi, avec seulement 1 piste stéréo, Spatgris, Reaper et Soundflower, mon automation écrite est reproduite dans le Zirkonium MKII même si l'interface spatgris est fermée. 

Cela sonne comme un problème de performance, potentiellement relié à soundflower, comme discuté dans un de tes emails, Robert...?

Le problème similaire qu'on avait était en mode audio, et non en mode osc spat (#52). 

Pour les tests approfondis, je vais déléguer à notre équipe de tests ;).

**Comment by Normandeau** [comment]
Test avec DP, 20 pistes stéréo, SpatGRIS partout.
J'ai fait comme j'ai dit: construction de la session piste par piste. Création d'une piste, insertion de SpatGRIS. Audio et OSC OK.
Je me suis rendu jusqu'à 20 pistes audio stéréo sans problème.
Puis j'ai fermé le tout, Zirkonium et DP.
Puis j'ai rouvert le tout comme il se passe quand on revient travailler sur un projet le lendemain.
Aucun audio, sauf à travers la sortie Aux destinée aux Subs.
(Nous utilisons une nouvelle méthodologie ici pour les subs. Au lieu de les assigner directement comme on le fait dans Jack, comme Soundflower ne comporte pas de matrice, on assigne les subs à un Aux, lui-même assigné aux entrées 63-64 de Zirkonium, eux-mêmes assignées à deux sorties directes vers les hp graves.)

![capture d ecran 2016-08-10 a 11 20 49](https://cloud.githubusercontent.com/assets/8959779/17559531/8d8fdb2e-5eec-11e6-8325-a7c3de066e59.jpg)

Donc ouverture de la session DP, aucun audio sauf à travers les Aux (donc vers les sorties 33-34 connectées aux Subs dans le dôme de la fac), autrement dit, vers deux sorties qui ne sont pas spatialisées dans le dôme.
C'est comme si Spatgris de manière assez mystérieuse, coupait l'audio du Zirkonium.
Car on voit bien dans les Inputs du Zirkonium qu'il y a de l'activité audio car les Vu-Mètres s'agitent.
Mais la seule façon de retrouver de l'audio est d'ouvrir l'interface visuelle des SpatGRIS, piste après piste. On peut ensuite refermer celle-ci, et alors l'audio continue de fonctionner même en arrière-plan.
Mais si on ferme et on rouvre la session, plus d'audio.

**Comment by vberthiaume** [comment]
À la ré-ouverture de DP, est-ce que les sources se déplacent dans le
zirkonium? Juste pour savoir si c'est l'audio ET l'osc qui ne fonctionnent
pas à la ré-ouverture...

2016-08-10 11:23 GMT-04:00 Robert Normandeau notifications@github.com:

**Comment by vberthiaume** [comment]
j'ai trouvé un bogue qui règle le problème pour l'osc, mais comme je suis chez moi je ne peux tester l'audio... Je fais une nouvelle version immédiatement.

**Comment by Normandeau** [comment]
Test rapide avec la même session.
Enregistrement de l'automation pour les deux premières pistes stéréo.
L'automation ne joue jamais quand la fenêtre de SpatGRIS est fermée. Même quand l'audio joue.
Pour que l'automation joue, la fenêtre doit être ouverte.
