### ISSUE TITLE
First Source ID et OSC Spat Port Boxes ne sont pas neutralisés par la touche Enter

### ISSUE THREAD

**Issue by Normandeau** [GRIS-UdeM/SpatGRIS-legacy#84]
Lorsqu'on entre des valeurs dans l'une ou l'autre de ces deux boites, le fait de taper Enter valide l'information mais la boite demeure active. Par exemple, on entre le no de la Source ID et qu'est-ce qu'on fait normalement après, on appuie sur la barre d’espacement pour lancer le séquenceur et qu'est-ce qui se passe? Rien. Parce c'est un espace qui a été entré dans la boite de Source ID. À corriger (on a déjà corrigé cela aussi...)

**Comment by vberthiaume** [comment]
Ah ouais, c'était réglé pour Reaper mais pas pour DP...! Ça sera réglé partout pour la prochaine version.
