### ISSUE TITLE
DP windows only recognizes mono and stereo modes, no surround modes

### ISSUE THREAD

**Issue by vberthiaume** [GRIS-UdeM/SpatGRIS-legacy#86]

**Comment by vberthiaume** [comment]
Potentiellement relié à https://github.com/GRIS-UdeM/SpatGRIS/issues/72

**Comment by Normandeau** [comment]
Sous Windows, tu n'as pas le choix d'utiliser la version VST n'est-ce pas? Or la version VST ne fonctionne pas non plus dans DP pour Mac. C'est à dire qu'aucun plugiciels multiphoniques  (les nôtres, les GRM, les Flux, etc) ne fonctionnent. J'ai déjà écrit à plusieurs reprises à MOTU à ce sujet, et même sur le forum. Silence radio... Il faudrait comparer avec la version Windows de Reaper. Pour voir si c'est la version VST Windows de Spatgris qui est en cause ou simplement DP avec les plugiciels multiphoniques VST.

**Comment by vberthiaume** [comment]
Bon point. D'après mes tests limités, la version vst windows fonctionne bien sous Reaper. Je mets ça sous "attente d'une solution externe".

**Comment by vberthiaume** [comment]
on regardera ça quand on aura des nouvelles de DP. Pour l'instant je ferme l'issue.
