### ISSUE TITLE
reaper: vst3 plante quand ajouté sur une piste

### ISSUE THREAD

**Issue by vberthiaume** [GRIS-UdeM/SpatGRIS-legacy#97]

**Comment by vberthiaume** [comment]
it seems that the problem is that with vst3s, preparetoplay is called over and over again, setting the number of ixo to 8x16, 2x2, then 1x1. Commenting the part in preparetoplay that does that makes the plugin load, but then we're in 12x12 instead of 8x16. so why don't we forget about the vst3s for now...!

**Comment by Normandeau** [comment]
On ne publie pas de version VST3 pour le moment.
